import { BaseTrickDefinition } from './types';

export const CATALOG_VERSION = '1.1.0';

export const BASE_TRICKS: BaseTrickDefinition[] = [
  {
    id: 'ollie',
    name: 'Ollie',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside', 'backside'],
    boardRotationDeg: 0,
    boardFlip: 'none',
    difficulty: 1,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Fundamental pop where board and rider leap into the air together.',
  },
  {
    id: 'kickflip',
    name: 'Kickflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside', 'backside'],
    boardRotationDeg: 0,
    boardFlip: 'kickflip',
    difficulty: 2,
    allowedModifiers: {
      bodyVarial: true, // Sex change
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Ollie with a toe-side longitudinal flip along the board axis.',
  },
  {
    id: 'heelflip',
    name: 'Heelflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside', 'backside'],
    boardRotationDeg: 0,
    boardFlip: 'heelflip',
    difficulty: 2,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Ollie with a heel-side longitudinal flip along the board axis.',
  },
  {
    id: 'double_kickflip',
    name: 'Double Kickflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside', 'backside'],
    boardRotationDeg: 0,
    boardFlip: 'double_kickflip',
    difficulty: 3,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Two full axial rotations along the board longitudinal axis.',
  },
  {
    id: 'pop_shuvit',
    name: 'Pop Shuvit',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside'], // Default pop shuvit is backside 180 board rotation
    boardRotationDeg: 180,
    boardFlip: 'none',
    difficulty: 2,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: '180-degree backside horizontal board spin popped into the air (backside omitted in everyday name).',
  },
  {
    id: 'frontside_pop_shuvit',
    name: 'Frontside Pop Shuvit',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside'], // Frontside 180 board rotation
    boardRotationDeg: 180,
    boardFlip: 'none',
    difficulty: 2,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: '180-degree frontside horizontal board spin pushed forward.',
  },
  {
    id: 'shuvit_360',
    name: '360 Shuvit',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside', 'frontside'],
    boardRotationDeg: 360,
    boardFlip: 'none',
    difficulty: 3,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Full 360-degree horizontal spin with no axial flip (combines with 180 body for Bigspin).',
  },
  {
    id: 'shuvit_540',
    name: '540 Shuvit',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside', 'frontside'],
    boardRotationDeg: 540,
    boardFlip: 'none',
    difficulty: 4,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: '540-degree horizontal spin with no axial flip (combines with body rotation for Bigger Spin or Gazelle Spin).',
  },
  {
    id: 'varial_kickflip',
    name: 'Varial Kickflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none'], // Combined BS 180 shuvit + kickflip
    boardRotationDeg: 180,
    boardFlip: 'kickflip',
    difficulty: 3,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Backside 180 pop shuvit combined simultaneously with a kickflip.',
  },
  {
    id: 'varial_heelflip',
    name: 'Varial Heelflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none'], // Combined FS 180 shuvit + heelflip
    boardRotationDeg: 180,
    boardFlip: 'heelflip',
    difficulty: 3,
    allowedModifiers: {
      bodyVarial: true,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Frontside 180 pop shuvit combined simultaneously with a heelflip.',
  },
  {
    id: 'hardflip',
    name: 'Hardflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none'], // Frontside 180 shuvit + kickflip
    boardRotationDeg: 180,
    boardFlip: 'kickflip',
    difficulty: 4,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true, // Enables late BS 180 Ghetto Bird
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'Frontside pop shuvit combined with a kickflip (with late BS 180 forms Ghetto Bird).',
  },
  {
    id: 'inward_heelflip',
    name: 'Inward Heelflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none'], // Backside 180 shuvit + heelflip
    boardRotationDeg: 180,
    boardFlip: 'heelflip',
    difficulty: 4,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'Backside pop shuvit combined with a heelflip between legs.',
  },
  {
    id: 'tre_flip',
    name: 'Tre Flip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside'], // 360 shuvit + kickflip (360 Flip / Bigflip)
    boardRotationDeg: 360,
    boardFlip: 'kickflip',
    difficulty: 4,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: '360 Backside Shuvit combined with a Kickflip / Tre Flip.',
  },
  {
    id: 'laser_flip',
    name: 'Laser Flip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside'], // FS 360 shuvit + heelflip
    boardRotationDeg: 360,
    boardFlip: 'heelflip',
    difficulty: 5,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'Frontside 360 shuvit combined with a heelflip.',
  },
  {
    id: 'nightmare_flip',
    name: 'Nightmare Flip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none'],
    boardRotationDeg: 180,
    boardFlip: 'double_kickflip',
    difficulty: 5,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'BS 180 shuvit combined with a double kickflip (Varial Double Flip).',
  },
  {
    id: 'bigspin',
    name: 'Bigspin',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside', 'frontside'],
    boardRotationDeg: 360,
    boardFlip: 'none',
    difficulty: 3,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: '360-degree shuvit accompanied by a 180-degree body rotation in the same direction.',
  },
  {
    id: 'bigger_spin',
    name: 'Bigger Spin',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside', 'frontside'],
    boardRotationDeg: 540,
    boardFlip: 'none',
    difficulty: 4,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: '540-degree shuvit accompanied by a 180-degree body rotation in the same direction.',
  },
  {
    id: 'bigflip',
    name: 'Bigflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside', 'frontside'],
    boardRotationDeg: 360,
    boardFlip: 'kickflip',
    difficulty: 5,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'rail', 'manual_pad'],
    description: 'BS 360 shuvit + kickflip + BS 180 body rotation (Backside Bigspin Flip).',
  },
  {
    id: 'bigger_flip',
    name: 'Bigger Flip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside'],
    boardRotationDeg: 540,
    boardFlip: 'kickflip',
    difficulty: 5,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'BS 540 shuvit + kickflip + BS 180 body rotation.',
  },
  {
    id: 'bigheel',
    name: 'Bigheel',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'frontside'],
    boardRotationDeg: 360,
    boardFlip: 'heelflip',
    difficulty: 5,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'FS 360 shuvit + heelflip + FS 180 body rotation (Frontside Bigspin Heelflip).',
  },
  {
    id: 'bigspin_inward_heelflip',
    name: 'Bigspin Inward Heelflip',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none', 'backside'],
    boardRotationDeg: 360,
    boardFlip: 'heelflip',
    difficulty: 5,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'BS 360 shuvit + heelflip + BS 180 body rotation (Big Inward Heel).',
  },
  {
    id: 'impossible',
    name: 'Impossible',
    allowedStances: ['regular', 'fakie', 'switch', 'nollie'],
    applicableDirections: ['none'], // Vertical end-over-end wrap
    boardRotationDeg: 360,
    boardFlip: 'vertical_wrap',
    difficulty: 4,
    allowedModifiers: {
      bodyVarial: false,
      landingManual: true,
      revert: true,
    },
    supportedObstacleTypes: ['flatground', 'ledge', 'manual_pad'],
    description: 'Vertical 360 wrap around the back finger with no horizontal spin.',
  },
  ...(['feather_flip','unpossible'] as const).map(id => ({
    id, name:id==='feather_flip'?'Feather Flip':'Unpossible',
    allowedStances:['regular','fakie','switch','nollie'] as BaseTrickDefinition['allowedStances'],
    applicableDirections:['none'] as BaseTrickDefinition['applicableDirections'],
    boardRotationDeg:0,boardFlip:'vertical_wrap' as const,difficulty:5,
    allowedModifiers:{bodyVarial:true,landingManual:true,revert:true},
    supportedObstacleTypes:['flatground'] as BaseTrickDefinition['supportedObstacleTypes'],
    description:id==='feather_flip'?'Lift into a partial vertical wrap, then reverse the board back flat before catching.':'A reverse vertical wrap around the front finger, distinct from a front-finger impossible.'
  })),
];

export function getBaseTrickById(id: string): BaseTrickDefinition | undefined {
  return BASE_TRICKS.find((t) => t.id === id);
}

// Reserved records are data-only and intentionally separate from playable tricks.
export { RESERVED_TRICKS, getReservedTrickById } from './reservedTrickCatalog';
export type { ReservedTrickDefinition } from './reservedTrickCatalog';
