import { ObstacleTrickDefinition, ObstacleType } from './types';

export const OBSTACLE_TRICKS: ObstacleTrickDefinition[] = [
  // --- BASIC GRINDS ---
  {
    id: '50_50',
    name: '50-50',
    category: 'basic_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'both_trucks',
    boardAngle: 'parallel',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit', 'frontside_pop_shuvit', 'varial_kickflip'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out', 'nollie_flip_out'],
    difficulty: 2,
    description: 'Both trucks grinding, board roughly parallel to the obstacle.',
  },
  {
    id: '5_0',
    name: '5-0',
    category: 'basic_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'parallel',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal', 'manual'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out', 'nollie_flip_out'],
    difficulty: 3,
    description: 'Rear truck grinding, front truck lifted.',
  },
  {
    id: 'nosegrind',
    name: 'Nosegrind',
    category: 'basic_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'front_truck',
    boardAngle: 'parallel',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal', 'nose_manual'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out', 'nollie_flip_out'],
    difficulty: 3,
    description: 'Front truck grinding, rear truck lifted.',
  },
  {
    id: 'crooked',
    name: 'Crooked Grind',
    category: 'basic_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'front_truck',
    boardAngle: 'crooked_near',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal', 'nose_manual'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out', 'nollie_flip_out'],
    difficulty: 3,
    description: 'Nosegrind position, but board angled with the tail toward the near side and nose pressed into the edge.',
  },
  {
    id: 'overcrook',
    name: 'Overcrook',
    category: 'basic_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'front_truck',
    boardAngle: 'crooked_far',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal', 'nose_manual'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out', 'nollie_flip_out'],
    difficulty: 4,
    description: 'Crooked position with the tail angled across to the far side.',
  },

  // --- DIPPED & ANGLED GRIND VARIATIONS ---
  {
    id: 'smith',
    name: 'Smith Grind',
    category: 'angled_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'dipped_near',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal', 'manual'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out'],
    difficulty: 4,
    description: 'Rear truck grinding + front truck dipped below the edge on the near side.',
  },
  {
    id: 'feeble',
    name: 'Feeble Grind',
    category: 'angled_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'dipped_far',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out'],
    difficulty: 4,
    description: 'Rear truck grinding + front truck extended across the obstacle on the far side (typically dipped on a rail).',
  },
  {
    id: 'suski',
    name: 'Suski Grind',
    category: 'angled_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'raised_near',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out'],
    difficulty: 4,
    description: 'Smith-like sideways angle, but front truck raised instead of dipped.',
  },
  {
    id: 'salad',
    name: 'Salad Grind',
    category: 'angled_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'raised_far',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out', 'kickflip_out'],
    difficulty: 4,
    description: 'Feeble-like sideways angle, but front truck raised instead of dipped.',
  },
  {
    id: 'willy',
    name: 'Willy Grind',
    category: 'angled_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'front_truck',
    boardAngle: 'dipped_near',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out'],
    difficulty: 3,
    description: 'Front truck grinding + rear truck dipped on the near side.',
  },
  {
    id: 'overwilly',
    name: 'Overwilly',
    category: 'angled_grind',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'front_truck',
    boardAngle: 'dipped_far',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'revert_fs', 'revert_bs', 'shuvit_out'],
    difficulty: 4,
    description: 'Front truck grinding + rear truck dipped on the far side.',
  },

  // --- SLIDES AND VARIATIONS ---
  {
    id: 'boardslide',
    name: 'Boardslide',
    category: 'slide',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'center_deck',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'revert_fs', 'revert_bs'],
    difficulty: 2,
    description: 'Center of deck sliding across the obstacle; front truck passes over during entry.',
  },
  {
    id: 'lipslide',
    name: 'Lipslide',
    category: 'slide',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'center_deck',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'rear_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'revert_fs', 'revert_bs'],
    difficulty: 3,
    description: 'Same center-deck sliding position; rear truck passes over during entry.',
  },
  {
    id: 'noseslide',
    name: 'Noseslide',
    category: 'slide',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'nose_deck',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'revert_fs', 'revert_bs', 'shuvit_out'],
    difficulty: 3,
    description: 'Nose of deck sliding on the edge.',
  },
  {
    id: 'tailslide',
    name: 'Tailslide',
    category: 'slide',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'tail_deck',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'revert_fs', 'revert_bs', 'kickflip_out'],
    difficulty: 4,
    description: 'Tail of deck sliding on the edge.',
  },
  {
    id: 'bluntslide',
    name: 'Bluntslide',
    category: 'slide',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'tail_blunt',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'both_trucks',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'kickflip_out', 'revert_fs', 'revert_bs'],
    difficulty: 5,
    description: 'Board crosses over the obstacle, locking the edge between the tail and rear wheels/truck.',
  },
  {
    id: 'nosebluntslide',
    name: 'Nosebluntslide',
    category: 'slide',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'nose_blunt',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'both_trucks',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'kickflip_out', 'revert_fs', 'revert_bs'],
    difficulty: 5,
    description: 'Corresponding lock using the nose and front wheels/truck.',
  },
  {
    id: 'darkslide',
    name: 'Darkslide',
    category: 'slide',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'griptape',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['kickflip', 'heelflip'],
    allowedExitTricks: ['clean', 'kickflip_out', 'to_fakie'],
    difficulty: 5,
    description: 'Board upside down, griptape sliding on the obstacle.',
  },
  {
    id: 'primo_slide',
    name: 'Primo Slide',
    category: 'slide',
    supportedObstacles: ['ledge', 'rail'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'primo',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'none',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['kickflip', 'heelflip', 'ollie'],
    allowedExitTricks: ['clean', 'to_fakie'],
    difficulty: 5,
    description: 'Board on its side, sliding in a primo position.',
  },
  {
    id: 'banana_slide',
    name: 'Banana Slide',
    category: 'slide',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'double_contact',
    boardAngle: 'perpendicular',
    whichTruckCrosses: 'front_truck',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip'],
    allowedExitTricks: ['clean', 'to_fakie'],
    difficulty: 4,
    description: 'Nose sliding on one obstacle and tail on another simultaneously.',
  },

  // --- ROTATIONAL ENTRIES THAT GET SPECIAL NAMES ---
  {
    id: 'hurricane',
    name: 'Hurricane Grind',
    category: 'rotational_entry',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'dipped_far',
    whichTruckCrosses: 'front_truck',
    entryRotation: '180',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'revert_fs', 'revert_bs'],
    difficulty: 5,
    description: '180 into a backward/fakie feeble position (traditionally turns back out to starting stance).',
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane Grind',
    category: 'rotational_entry',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['frontside', 'backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'dipped_near',
    whichTruckCrosses: 'none',
    entryRotation: 'alley_oop_180',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip'],
    allowedExitTricks: ['clean', 'to_fakie', 'revert_fs', 'revert_bs'],
    difficulty: 5,
    description: 'Alley-oop 180 into a backward/fakie Smith position.',
  },
  {
    id: 'bennett',
    name: 'Bennett Grind',
    category: 'rotational_entry',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['frontside'],
    contactPoint: 'rear_truck',
    boardAngle: 'dipped_near',
    whichTruckCrosses: 'front_truck',
    entryRotation: 'bs_180',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip'],
    allowedExitTricks: ['clean', 'revert_bs', 'kickflip_out'],
    difficulty: 5,
    description: 'Frontside approach + BS 180 into switch BS Smith.',
  },
  {
    id: 'barley',
    name: 'Barley Grind',
    category: 'rotational_entry',
    supportedObstacles: ['rail', 'ledge'],
    applicableApproaches: ['backside'],
    contactPoint: 'rear_truck',
    boardAngle: 'dipped_near',
    whichTruckCrosses: 'front_truck',
    entryRotation: 'fs_180',
    landingPositionsAllowed: ['normal'],
    allowedEntryTricks: ['ollie', 'kickflip'],
    allowedExitTricks: ['clean', 'revert_fs', 'kickflip_out'],
    difficulty: 5,
    description: 'Backside approach + FS 180 into switch FS Smith.',
  },
];

export const MANUAL_PAD_OPTIONS = [
  { id: 'manual', name: 'Manual', allowedEntries: ['ollie', 'kickflip', 'heelflip', 'pop_shuvit'], allowedExits: ['clean', 'ollie_out', 'kickflip_out', 'revert_fs', 'revert_bs'] },
  { id: 'nose_manual', name: 'Nose Manual', allowedEntries: ['ollie', 'kickflip', 'heelflip', 'frontside_pop_shuvit'], allowedExits: ['clean', 'nollie_out', 'kickflip_out', 'revert_fs', 'revert_bs'] },
];

export function getObstacleTrickById(id: string): ObstacleTrickDefinition | undefined {
  return OBSTACLE_TRICKS.find((t) => t.id === id);
}

export function getObstacleTricksForObstacle(obstacle: ObstacleType): ObstacleTrickDefinition[] {
  return OBSTACLE_TRICKS.filter((t) => t.supportedObstacles.includes(obstacle));
}
