import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Target,Zap} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {riderProgression} from '../../domain/riderProgression';
import {PracticeTarget,suggestionFor,createTarget,targetAchieved} from '../../domain/practiceTargets';
import {SharedChallengeBar} from '../common/SharedChallengeBar';

export function ProgressionPanel() {
 const {sessions,profile,updateProfile,startPracticeTarget,currentSession,setActiveTab}=useApp();
 const [now,setNow]=useState(Date.now()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[alternatives,setAlternatives]=useState(false),[confirm,setConfirm]=useState<PracticeTarget|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const progress=useMemo(()=>riderProgression(sessions,now),[sessions,now]);
 const suggestion=useMemo(()=>suggestionFor(sessions,profile,now),[sessions,profile?.trickLibrary,now]);
 const target=profile?.practiceTarget||suggestion;
 const achieved=!!profile?.practiceTarget&&targetAchieved(sessions,target,now);
 const save=async(next:PracticeTarget,start=false,confirmed=false)=>{
  if(!profile||busy)return;
  if(start&&currentSession?.sessionStartedAt&&!currentSession.sessionEndedAt&&!confirmed){setConfirm(next);return;}
  setBusy(true);setError('');
  try{await updateProfile({...profile,practiceTarget:next});if(start)await startPracticeTarget(next);setConfirm(null);}
  catch(e){setError(e instanceof Error?e.message:'Could not save your target. Please retry.');}
  finally{setBusy(false);}
 };
 const button='min-h-12 rounded-lg bg-[#D4A72C] px-4 py-3 font-semibold text-black text-sm cursor-pointer hover:bg-[#e1b841] disabled:opacity-50 disabled:cursor-not-allowed';
 return <section aria-labelledby="breakthrough-heading" className="ds-surface rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 sm:p-6 space-y-5">
  <div className="flex flex-wrap justify-between gap-3 items-center"><p className="flex items-center gap-2 text-xs font-semibold tracking-widest uppercase text-[#8A6500] dark:text-[#D4A72C]"><Target size={16}/>Your next breakthrough</p><span className="inline-flex items-center gap-2 text-xs text-neutral-600 dark:text-neutral-400"><Zap size={14} className="text-[#D4A72C]"/>Level {progress.level.level} · {progress.totalXP} XP</span></div>
  <div className="space-y-3"><h2 id="breakthrough-heading" className="text-xl sm:text-2xl font-bold break-words">{achieved?'You reached your saved target.':target.title}</h2><p className="text-sm sm:text-base leading-7 text-neutral-600 dark:text-neutral-300">{achieved?`Completed: ${target.title}. ${suggestion.reason}`:target.reason}</p>{profile?.practiceTarget&&<p className="text-xs text-[#8A6500] dark:text-[#D4A72C]">{achieved?'Recorded in your finished session history. Choose your next step below.':'Saved to your account. Ready when you are.'}</p>}</div>
  {confirm?<div className="rounded-xl border border-[#D4A72C]/40 p-4 space-y-3"><p className="text-sm leading-6">Your current session will be paused and kept in history. Start this target instead?</p><div className="flex flex-wrap gap-3"><button disabled={busy} className={button} onClick={()=>void save(confirm,true,true)}>Pause current & continue</button><button disabled={busy} className="min-h-12 px-4 cursor-pointer" onClick={()=>setConfirm(null)}>Keep current session</button></div></div>:<div className="flex flex-col sm:flex-row gap-3"><button disabled={busy} className={button} onClick={()=>void save(achieved?suggestion:target,true)}>{busy?'Saving…':achieved?'Take the next challenge':'Take the challenge'}</button><button type="button" disabled={busy} className="min-h-12 px-4 text-sm underline underline-offset-4 cursor-pointer" aria-expanded={alternatives} onClick={()=>setAlternatives(v=>!v)}>Choose another goal</button></div>}
  {alternatives&&<div className="rounded-xl border border-neutral-300 dark:border-neutral-700 p-4 space-y-4"><button type="button" className="min-h-11 text-sm underline underline-offset-4 cursor-pointer" onClick={()=>setActiveTab('generator')}>Change trick in Trick Lab</button><fieldset disabled={busy} className="space-y-3"><legend className="text-sm font-semibold mb-3">Or pick a quick mission for {target.trickResult.canonicalName}</legend><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{([{type:'landings',target:5,title:'Five landings',detail:'Build a little repetition.'},{type:'streak',target:3,title:'Three in a row',detail:'Focus on consistency.'},{type:'time',target:10,title:'Ten minutes',detail:'Make time for practice.'}] as const).map(mission=><button key={mission.type} type="button" className="min-h-20 rounded-xl border border-neutral-300 dark:border-neutral-700 p-4 text-left cursor-pointer hover:border-[#D4A72C] focus-visible:outline-2 focus-visible:outline-[#D4A72C] disabled:opacity-50" onClick={()=>void save(createTarget(target.trickResult,{type:mission.type,target:mission.target},mission.detail),true)}><span className="block font-semibold text-sm">{mission.title}<ArrowRight className="inline ml-2 text-[#D4A72C]" size={15}/></span><span className="block mt-2 text-xs text-neutral-600 dark:text-neutral-400">{mission.detail}</span></button>)}</div></fieldset></div>}
  {error&&<p role="alert" className="text-sm text-rose-600 dark:text-rose-400">{error}</p>}
  <details className="progression-disclosure border border-neutral-200 dark:border-neutral-800 rounded-xl p-4"><summary className="cursor-pointer text-sm font-semibold">Want a different practice challenge?</summary><p className="mt-3 text-sm text-neutral-500 leading-6">Shuffle a fixed deck of tricks. Play five tries per card or test yourself in Game of SKATE.</p><button type="button" className="min-h-11 mt-2 text-sm underline underline-offset-4 cursor-pointer" onClick={()=>setActiveTab('games')}>Play a practice deck <ArrowRight size={15} className="inline ml-2"/></button></details>
  <details className="progression-disclosure border border-neutral-200 dark:border-neutral-800 rounded-xl p-4"><summary className="cursor-pointer text-sm font-semibold">Level {progress.level.level}: {progress.level.title} · {progress.level.remaining} XP to the next level</summary><div className="mt-3 space-y-3"><progress aria-label="Rider level progress" className="ds-progress w-full h-2 accent-[#D4A72C]" max={progress.level.ceiling-progress.level.floor} value={progress.level.xp-progress.level.floor}/><p className="text-xs leading-6 text-neutral-600 dark:text-neutral-400">Focused sessions earn 20 XP (first five per UTC+8 day). First recorded landings earn 40 XP. New streak and rate records earn 20 and 25 XP, once per variation per week. Community completions earn 25 XP. Failed goals still count as practice; parked sessions wait until finished. Imported history counts, and corrections recalculate XP. Levels reflect recorded practice, not skill rank.</p></div></details>
  <div className="border-t border-neutral-200 dark:border-neutral-800 pt-4 space-y-3"><h3 className="font-semibold text-sm">Want a shared challenge instead?</h3><SharedChallengeBar inline/></div>
 </section>;
}
