import React,{useState} from 'react';
import {Modal} from '../common/Modal';
import {trickKey} from '../../domain/progression';
import {formatDurationMs} from '../../domain/timer';
import {useApp} from '../../context/AppContext';
import {HW_BUTTON} from '../settings/HardwareManager';
import {PracticeSession} from '../../domain/types';
export function homePracticeStats(sessions:PracticeSession[]){
 const started=sessions.filter(s=>!!s.sessionStartedAt&&Number.isFinite(Date.parse(s.sessionStartedAt)));
 const attempts=started.reduce((n,s)=>n+s.attemptCount,0),landings=started.reduce((n,s)=>n+s.landingCount,0);
 return {practiceTime:formatDurationMs(started.reduce((sum,s)=>sum+(Number.isFinite(s.activeDurationMs)?Math.max(0,s.activeDurationMs):0),0)),uniqueLanded:new Set(started.filter(s=>s.landingCount>0&&s.trickResult).map(s=>trickKey(s.trickResult))).size,count:started.length,landings,rate:attempts?`${(landings/attempts*100).toFixed(1)}%`:'—',best:Math.max(0,...started.map(s=>s.bestLandingStreak||0)),recent:[...started].sort((a,b)=>Date.parse(b.sessionStartedAt!)-Date.parse(a.sessionStartedAt!))[0]};
}
export function RiderHomeSummary(){
 const {sessions,profile,setActiveTab,updateProfile,showToast}=useApp();const stats=homePracticeStats(sessions);
 const [choosing,setChoosing]=useState(false),[selectedId,setSelectedId]=useState(''),[busy,setBusy]=useState(false);
 const setup=profile?.savedSetups.find(s=>s.id===profile.showcase?.featuredSetupId);
 const card='bg-white dark:bg-neutral-900 rounded-xl border border-neutral-200 dark:border-neutral-800 p-4 sm:p-6 space-y-2 sm:space-y-4 min-w-0';
 return <section aria-labelledby="home-progress-heading" className="space-y-5"><div className="space-y-3"><p className="text-[10px] sm:text-xs uppercase tracking-[0.18em] font-semibold text-[#8A6500] dark:text-[#D4A72C]">Your practice · Your progress</p><h2 id="home-progress-heading" className="text-2xl sm:text-3xl font-bold tracking-tight">Your riding at a glance</h2><p className="text-sm text-neutral-500 mt-1">All-time progress from your started practice sessions.</p></div><div className="grid grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-4">
 {([['Total sessions',stats.count],['Successful landings',stats.landings],['Overall landing rate',stats.rate],['Best landing streak',stats.best],['Total practice time',stats.practiceTime],['Distinct tricks landed',stats.uniqueLanded]] as const).map(([label,value],index)=><article key={label} className={card}><span className="block text-[10px] font-mono tracking-widest text-[#8A6500] dark:text-[#D4A72C]">{String(index+1).padStart(2,'0')}</span><h3 className="text-xs sm:text-sm text-neutral-600 dark:text-neutral-400">{label}</h3><p className="text-2xl sm:text-3xl font-semibold text-[#8A6500] dark:text-[#D4A72C]">{value}</p>{label==='Overall landing rate'&&<p className="text-xs text-neutral-500">Successful landings / total attempts</p>}{label==='Total practice time'&&<p className="text-xs text-neutral-500">Recorded active time · pauses excluded</p>}{label==='Distinct tricks landed'&&<p className="text-xs text-neutral-500">Each variation or combo counts once</p>}</article>)}
 <article className={`${card} col-span-2 xl:col-span-1`}><span className="block text-[10px] font-mono tracking-widest text-[#8A6500] dark:text-[#D4A72C]">07</span><h3 className="text-xs sm:text-sm text-neutral-600 dark:text-neutral-400">Featured setup</h3>{setup?<><p className="text-xl font-semibold break-words">{setup.name}</p><p className="text-sm text-neutral-500">{setup.deckWidthMm||'Unknown'} mm · {setup.wheelMaterial.charAt(0).toUpperCase()+setup.wheelMaterial.slice(1)} wheels</p></>:<p className="text-sm text-neutral-500">Choose the setup you want to showcase here.</p>}<button className={HW_BUTTON} onClick={()=>{setSelectedId(profile?.showcase?.featuredSetupId||'');setChoosing(true);}}>{setup?'Change featured setup':'Choose featured setup'}</button></article>
 <article className={`${card} col-span-2 xl:col-span-1`}><span className="block text-[10px] font-mono tracking-widest text-[#8A6500] dark:text-[#D4A72C]">08</span><h3 className="text-xs sm:text-sm text-neutral-600 dark:text-neutral-400">Most recent practice session</h3>{stats.recent?<><p className="text-xl font-semibold break-words">{stats.recent.trickResult.canonicalName}</p><p className="text-xs text-neutral-500">{new Date(stats.recent.sessionStartedAt!).toLocaleDateString()} · {stats.recent.landingCount} / {stats.recent.attemptCount} landings · {stats.recent.status}</p></>:<p className="text-sm text-neutral-500">Start your first session in Trick Lab.</p>}<button className={HW_BUTTON} onClick={()=>setActiveTab(stats.recent?'history':'generator')}>{stats.recent?'View practice history':'Start practicing'}</button></article>
 </div><Modal isOpen={choosing} onClose={()=>{if(!busy)setChoosing(false);}} title="Choose your featured setup"><form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(!profile||busy)return;setBusy(true);try{await updateProfile({...profile,showcase:{...(profile.showcase||{bio:'',goal:'',accent:'mustard',featuredTricks:[],featuredMilestones:[],showStats:true}),featuredSetupId:selectedId}});setChoosing(false);showToast('Featured setup updated.');}catch{showToast('Could not update featured setup. Try again.');}finally{setBusy(false);}}}><p className="text-sm text-neutral-500">Showcase one setup on your homepage and rider profile. Favorites remain separate.</p><label className="block text-sm font-semibold">Featured setup<select disabled={busy} value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="mt-2 w-full rounded-lg border border-neutral-300 dark:border-neutral-700 bg-transparent p-3"><option value="">None</option>{profile?.savedSetups.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{!profile?.savedSetups.length&&<button type="button" className={HW_BUTTON} onClick={()=>{setChoosing(false);setActiveTab('settings');}}>Add a fingerboard setup</button>}<button disabled={busy} className={HW_BUTTON} type="submit">{busy?'Saving…':'Save featured setup'}</button></form></Modal></section>;
}
