import React, {useState} from 'react';
import { GeneratedTrickResult } from '../../domain/types';
import { trickKey, LEARNING_STATUSES } from '../../domain/progression';
export type PoolSource = 'parameters'|'custom'|'library';
export const SelectedTrickPool: React.FC<{source:PoolSource;onSource:(source:PoolSource)=>void;items:GeneratedTrickResult[];selected:string[];onSelected:(keys:string[])=>void;stances:('regular'|'nollie'|'fakie'|'switch')[];onStances:(value:('regular'|'nollie'|'fakie'|'switch')[])=>void;stanceVariations:boolean;onStanceVariations:(value:boolean)=>void;rotationVariations:boolean;onRotationVariations:(value:boolean)=>void;rotations:('none'|'frontside'|'backside')[];onRotations:(value:('none'|'frontside'|'backside')[])=>void;status:string;onStatus:(status:string)=>void}> = ({source,onSource,items,selected,onSelected,status,onStatus,stances,onStances,stanceVariations,onStanceVariations,rotationVariations,onRotationVariations,rotations,onRotations}) => {
 const [search,setSearch]=useState('');
 const visible=items.filter(t=>t.canonicalName.toLowerCase().includes(search.trim().toLowerCase()));
 const input='rounded-md border border-neutral-300 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800 px-3 py-2 text-sm';
 const button='cursor-pointer rounded-md border border-[#D4A72C] px-3 py-2 text-xs text-[#8A6500] dark:text-[#D4A72C] hover:bg-[#D4A72C] hover:text-neutral-950';
 return <section className="ds-surface rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4 sm:p-5 space-y-4">
  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><h2 className="font-semibold">Generate from</h2><div role="group" aria-label="Generation source" className="grid grid-cols-1 sm:flex sm:flex-wrap gap-2 w-full sm:w-auto">{([{id:'parameters',label:'Parameters & locks'},{id:'custom',label:'Selected trick pool'},{id:'library',label:'Personal trick library'}] as const).map(option=><button key={option.id} type="button" aria-pressed={source===option.id} onClick={()=>onSource(option.id)} className={`cursor-pointer rounded-lg border px-4 py-3 sm:px-3 sm:py-2 text-sm sm:text-xs text-left sm:text-center font-semibold transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#D4A72C] ${source===option.id?'border-[#D4A72C] bg-[#D4A72C]/10 text-[#8A6500] dark:text-[#D4A72C]':'border-neutral-300 dark:border-neutral-700 text-neutral-700 dark:text-neutral-300 hover:border-[#D4A72C]/60'}`}>{option.label}</button>)}</div></div>
  {source!=='parameters'&&<>
   <p className="text-xs text-neutral-500 dark:text-neutral-400">Pick exact challenges to shuffle between. Modifiers and obstacle stay as selected. Custom single-trick pools can include valid stance and rotation variations below. Each eligible trick has an equal chance; repeats are possible. Session mode and skate class still apply. Parameter locks and pools apply only to Parameters & locks.</p>
   {source==='custom'&&<div className="space-y-3 text-sm">
    <label className="flex gap-2 items-center cursor-pointer"><input type="checkbox" className="accent-[#D4A72C]" checked={stanceVariations} onChange={e=>onStanceVariations(e.target.checked)}/>Include stance variations (regular, fakie, switch, nollie)</label>
    {stanceVariations&&<div className="flex flex-wrap gap-4 pl-6">{(['regular','nollie','fakie','switch'] as const).map(stance=><label key={stance} className="flex items-center gap-2 cursor-pointer"><input type="checkbox" className="accent-[#D4A72C]" checked={stances.includes(stance)} onChange={()=>onStances(stances.includes(stance)?stances.filter(s=>s!==stance):[...stances,stance])}/>{stance.charAt(0).toUpperCase()+stance.slice(1)}</label>)}</div>}
    <label className="flex gap-2 items-center cursor-pointer"><input type="checkbox" className="accent-[#D4A72C]" checked={rotationVariations} onChange={e=>onRotationVariations(e.target.checked)}/>Include rotation variations where applicable</label>
    {rotationVariations&&<div className="flex flex-wrap gap-4 pl-6">{(['none','frontside','backside'] as const).map(direction=><label key={direction} className="flex items-center gap-2 cursor-pointer"><input type="checkbox" className="accent-[#D4A72C]" checked={rotations.includes(direction)} onChange={()=>onRotations(rotations.includes(direction)?rotations.filter(d=>d!==direction):[...rotations,direction])}/>{direction==='none'?'None':direction==='frontside'?'FS':'BS'}</label>)}</div>}
    <p className="text-xs text-neutral-500">Applies to single tricks only. Unsupported variations are skipped. Unchecked options keep the selected trick’s original stance or rotation.</p>
   </div>}
   <div className="flex flex-wrap gap-2"><input className={`${input} flex-1 min-w-0`} aria-label="Search selected trick pool" placeholder="Search tricks" value={search} onChange={e=>setSearch(e.target.value)}/>{source==='library'&&<select aria-label="Library learning status" className={input} value={status} onChange={e=>onStatus(e.target.value)}><option value="all">All learning statuses</option>{LEARNING_STATUSES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select>}</div>
   <div className="flex flex-wrap items-center gap-2"><button type="button" className={button} onClick={()=>onSelected([...new Set([...selected,...visible.map(trickKey)])])}>Select All{search?' matches':''}</button><button type="button" className={button} onClick={()=>onSelected(selected.filter(k=>!visible.some(t=>trickKey(t)===k)))}>Select None{search?' matches':''}</button><span className="text-xs text-neutral-500">{items.filter(t=>selected.includes(trickKey(t))).length} eligible selections</span></div>
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-72 overflow-y-auto pr-1">{visible.map(t=>{const key=trickKey(t);return <label key={key} className="cursor-pointer flex items-start gap-3 rounded-lg border border-neutral-200 dark:border-neutral-700 p-3 text-sm"><input type="checkbox" className="mt-1 accent-[#D4A72C] cursor-pointer" checked={selected.includes(key)} onChange={()=>onSelected(selected.includes(key)?selected.filter(k=>k!==key):[...selected,key])}/><span className="break-words">{t.canonicalName}</span></label>;})}</div>
   {!visible.length&&<p className="text-sm text-neutral-500">{source==='library'?'No library tricks match. Add tricks in Trick Library or change your filters.':'No tricks match. Base tricks are available in Single Trick; combos and obstacle challenges appear after saving them to your history or bookmarks.'}</p>}
  </>}
 </section>;
};
