import type {DeckMode} from '../../domain/deckGame';
import './SessionStartWizard.css';
import {Clock, Layers, MapPin, ArrowRight, Sparkles, Trophy} from 'lucide-react';
import {goalLabel} from '../../domain/practiceTargets';
import {practiceDefaults} from '../../domain/practiceDefaults';
import React,{useState} from 'react';
import {Modal} from '../common/Modal';
import {useApp} from '../../context/AppContext';
import {SetupEditor,HW_INPUT,HW_BUTTON} from '../settings/HardwareManager';
import {SURFACES} from '../../domain/hardware';
import {PracticeSession,SetupData} from '../../domain/types';
import {startConfiguredSession} from '../../domain/sessionPlan';
export function SessionStartWizard({session,onStart,onClose,demoSetups,gameSetup,gameMode,gameDefaults,onBack}:{onBack?:()=>void;gameMode?:DeckMode;gameDefaults?:{setupId:string;surface:string};gameSetup?:string;demoSetups?:SetupData[];session:PracticeSession;onStart:(s:PracticeSession)=>Promise<void>;onClose:()=>void}){
 const {profile:accountProfile,updateProfile,sessions}=useApp();
 const profile=demoSetups?{savedSetups:demoSetups}:accountProfile;
 const [defaults]=useState(()=>{const defaults=practiceDefaults(session,demoSetups?[]:sessions,profile?.savedSetups||[]);return gameDefaults?{...defaults,setupId:profile?.savedSetups.some(s=>s.id===gameDefaults.setupId)?gameDefaults.setupId:defaults.setupId,surface:gameDefaults.surface}:defaults;});
 const [chosen,C]=useState(defaults.setupId),[adding,A]=useState(false),[goal,G]=useState(defaults.goal.type),[target,T]=useState(defaults.goal.target),[timer,Y]=useState(defaults.timer.type),[minutes,M]=useState(Math.floor((defaults.timer.durationMs||300000)/60000)),[seconds,X]=useState(Math.floor((defaults.timer.durationMs||300000)/1000)%60),[surface,F]=useState(SURFACES.includes(defaults.surface)?defaults.surface:defaults.surface?'Other':''),[custom,U]=useState(defaults.surface),[busy,B]=useState(false),[error,E]=useState('');
 if(!profile)return null;
 const ModeIcon=gameMode==='skate'?Trophy:gameMode==='wildcard'?Sparkles:Layers;
 const setup=profile.savedSetups.find(s=>s.id===chosen);
 const quick=(type:typeof goal,value:number)=>{G(type);T(value);if(type==='time'){Y('countdown');M(value);X(0);}};
 const start=async()=>{E('');if(!setup){E('Choose a saved setup or add one.');return;}B(true);try{if(timer==='countdown'&&(!Number.isInteger(minutes)||!Number.isInteger(seconds)||minutes<0||seconds<0||seconds>59))throw Error('Enter whole minutes and seconds (0–59).');await onStart(startConfiguredSession(session,setup,{type:gameSetup?'landings':goal,target:gameSetup?1:target},gameSetup?{type:'regular'}:{type:timer,...(timer==='countdown'?{durationMs:(minutes*60+seconds)*1000}:{})},surface==='Other'?custom:surface));}catch(e){E(e instanceof Error?e.message:'Could not start.');}finally{B(false);}};
 return <Modal isOpen onClose={()=>{if(!busy)onClose();}} title={adding?'Configure a fingerboard':gameSetup?'Ready to start your session?':'Ready to practice?'}>{adding?<SetupEditor onCancel={()=>A(false)} onSave={async(s:SetupData)=>{if(accountProfile&&!demoSetups)await updateProfile({...accountProfile,savedSetups:[...accountProfile.savedSetups,s]});C(s.id);A(false);}}/>:<div className={`session-start-dialog space-y-5 ${demoSetups?'demo-white-controls':''}`}>
 <header className="session-start-intro"><span className="session-start-medal"><ModeIcon size={28} aria-hidden="true"/></span><p className="session-start-eyebrow">SESSION SETUP</p><h3>{gameSetup||session.trickResult.canonicalName}</h3><p>{gameSetup?'Choose your setup and surface. The same settings apply to every card.':'Choose your setup, goal, and surface before you start.'}</p><span className="session-start-timer"><Clock size={14}/>{gameSetup?'Regular session timer':goalLabel({type:goal,target})}</span><p className="session-start-confirmation">The timer starts only when you confirm.</p></header>
 <fieldset disabled={busy} className={`session-start-fields ${gameSetup?'is-deck-session':''}`}>
 <section className="session-start-setting"><div className="session-start-setting-heading"><Layers size={18}/><span>YOUR FINGERBOARD</span></div><label className="block text-sm font-semibold">Fingerboard setup<select className={HW_INPUT} value={chosen} onChange={e=>C(e.target.value)}><option value="">Choose a setup</option>{[...profile.savedSetups].sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite)).map(s=><option key={s.id} value={s.id}>{s.favorite?'★ ':''}{s.name} · {s.deckWidthMm||'?'} mm</option>)}</select></label>{!demoSetups&&<button type="button" className="min-h-11 text-sm underline underline-offset-4 cursor-pointer" onClick={()=>A(true)}>+ Add setup / parts</button>}</section>
 {!gameSetup&&<>
 <details className="rounded-xl border border-neutral-300 dark:border-neutral-700 p-4"><summary className="cursor-pointer text-sm font-semibold">Goal · {goalLabel({type:goal,target})}</summary><div className="mt-4 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-3 gap-2">{([{type:'landings',target:5,label:'Five landings'},{type:'streak',target:3,label:'Three in a row'},{type:'time',target:10,label:'Ten minutes'}] as const).map(m=><button type="button" key={m.type} aria-pressed={goal===m.type&&target===m.target} className={`min-h-12 rounded-lg border px-3 py-3 text-sm cursor-pointer ${goal===m.type&&target===m.target?'border-[#D4A72C]':'border-neutral-300 dark:border-neutral-700'}`} onClick={()=>quick(m.type,m.target)}>{m.label}</button>)}</div><label className="block text-sm">Goal type<select className={HW_INPUT} value={goal} onChange={e=>quick(e.target.value as typeof goal,e.target.value==='time'?10:3)}><option value="landings">Total successful landings</option><option value="streak">Successful landings in a row</option><option value="time">Active practice minutes</option></select></label><label className="block text-sm">Target<input type="number" min={1} max={goal==='time'?1440:10000} step={1} className={HW_INPUT} value={target} onChange={e=>T(Number(e.target.value))}/></label></div></details>
 <details className="rounded-xl border border-neutral-300 dark:border-neutral-700 p-4"><summary className="cursor-pointer text-sm font-semibold">Timer · {timer==='regular'?'Regular practice':`${minutes}m ${seconds}s countdown`}</summary><div className="mt-4 space-y-3"><label className="block text-sm">Timer<select className={HW_INPUT} value={timer} onChange={e=>Y(e.target.value as typeof timer)}><option value="regular">Regular practice timer</option><option value="countdown">Countdown — ends automatically</option></select></label>{timer==='countdown'&&<div className="grid grid-cols-2 gap-3"><label className="text-sm">Minutes<input className={HW_INPUT} type="number" min={0} max={1440} step={1} value={minutes} onChange={e=>M(Number(e.target.value))}/></label><label className="text-sm">Seconds<input className={HW_INPUT} type="number" min={0} max={59} step={1} value={seconds} onChange={e=>X(Number(e.target.value))}/></label></div>}</div></details>
 </>}
 <section className="session-start-setting"><div className="session-start-setting-heading"><MapPin size={18}/><span>YOUR SURFACE</span></div><label className="block text-sm font-semibold">Surface Material<select className={HW_INPUT} value={surface} onChange={e=>F(e.target.value)}><option value="">Choose a surface</option>{SURFACES.map(s=><option key={s}>{s}</option>)}</select></label><p className="session-start-surface-help">Choose the material you’re riding on to compare your results across surfaces.</p>{surface==='Other'&&<label className="block text-sm">Custom surface<input className={HW_INPUT} value={custom} maxLength={100} onChange={e=>U(e.target.value)}/></label>}</section>
 </fieldset>{error&&<p role="alert" className="text-red-500 text-sm">{error}</p>}<div className="session-start-actions flex gap-3"><button data-demo-navigation className={HW_BUTTON} disabled={busy} onClick={onBack||onClose}>{onBack?'Back':'Cancel'}</button><button type="button" className="min-h-12 flex-1 rounded-lg bg-[#D4A72C] text-black px-4 py-3 font-semibold cursor-pointer hover:bg-[#e1b841] disabled:opacity-50" disabled={busy} onClick={()=>void start()}>{busy?'Starting…':gameSetup?'Start Session':'Start practice'}{!busy&&<ArrowRight size={17} aria-hidden="true"/>}</button></div>
 </div>}</Modal>;
}
