import React,{useState} from 'react';
import {Modal} from '../common/Modal';
import {useApp} from '../../context/AppContext';
import {SetupEditor,HW_INPUT,HW_BUTTON} from '../settings/HardwareManager';
import {SURFACES} from '../../domain/hardware';
import {PracticeSession,SetupData} from '../../domain/types';
import {startConfiguredSession} from '../../domain/sessionPlan';
export function SessionStartWizard({session,onStart,onClose,demoSetups}:{demoSetups?:SetupData[];session:PracticeSession;onStart:(s:PracticeSession)=>Promise<void>;onClose:()=>void}){
 const {profile:accountProfile,updateProfile}=useApp();
 const profile=demoSetups?{savedSetups:demoSetups}:accountProfile;const [step,S]=useState(0),[chosen,C]=useState(''),[adding,A]=useState(false),[goal,G]=useState<'landings'|'streak'>('landings'),[target,T]=useState(session.sharedChallenge?.targetLandings||3),[timer,Y]=useState<'regular'|'countdown'>('regular'),[minutes,M]=useState(5),[seconds,X]=useState(0),[surface,F]=useState(''),[custom,U]=useState(''),[busy,B]=useState(false),[error,E]=useState('');
 if(!profile)return null;const setup=profile.savedSetups.find(s=>s.id===chosen);
 const titles=['Choose your fingerboard','Set a landing goal','Choose your timer','Choose your practice surface'];
 const next=async()=>{E('');if(step===0&&!setup){E('Choose a saved setup or add one.');return;}if(step===1&&(!Number.isInteger(target)||target<1||target>10000)){E('Enter a whole number from 1 to 10,000.');return;}if(step===2&&timer==='countdown'&&(!Number.isInteger(minutes)||!Number.isInteger(seconds)||seconds<0||seconds>59||minutes<0||(minutes*60+seconds)<1||(minutes*60+seconds)>86400)){E('Choose a countdown from 1 second to 24 hours.');return;}if(step<3){S(step+1);return;}B(true);try{await onStart(startConfiguredSession(session,setup!,{type:goal,target},{type:timer,...(timer==='countdown'?{durationMs:(minutes*60+seconds)*1000}:{})},surface==='Other'?custom:surface));}catch(e){E(e instanceof Error?e.message:'Could not start.');}finally{B(false);}};
 return <Modal isOpen onClose={()=>{if(!busy)onClose();}} title={adding?'Configure a fingerboard':titles[step]}>{adding?<SetupEditor onCancel={()=>A(false)} onSave={async(s:SetupData)=>{if(accountProfile&&!demoSetups)await updateProfile({...accountProfile,savedSetups:[...accountProfile.savedSetups,s]});C(s.id);A(false);}}/>:<div className={`space-y-5 ${demoSetups?'demo-white-controls':''}`}><p className="text-xs text-neutral-500">Step {step+1} / 4 · Your timer starts after setup is complete.</p>
 {step===0&&<><div className="space-y-3">{[...profile.savedSetups].sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite)).map(s=><label key={s.id} className="flex gap-3 items-center border border-neutral-300 dark:border-neutral-700 rounded-lg p-4 cursor-pointer"><input type="radio" name="setup" checked={chosen===s.id} onChange={()=>C(s.id)}/><span>{s.favorite?'★ ':''}{s.name}<small className="block text-neutral-500">{s.deckWidthMm||'Unknown'} mm · {s.wheelMaterial} wheels</small></span></label>)}</div>{!demoSetups&&<button className={HW_BUTTON} onClick={()=>A(true)}>+ Add setup / parts</button>}{demoSetups&&<p className="text-xs text-neutral-500">Sample setups for this preview. Your own setups can be added after signing in.</p>}</>}
 {step===1&&<div className="space-y-4"><label className="block">What would make this session successful?<select className={HW_INPUT} value={goal} onChange={e=>G(e.target.value as typeof goal)}><option value="landings">Total successful landings</option><option value="streak">Successful landings in a row</option></select></label><label className="block">Target<input type="number" min={1} max={10000} step={1} className={HW_INPUT} value={target} onChange={e=>T(Number(e.target.value))}/></label><p className="text-xs text-neutral-500">Your final result is based on reaching this goal. A streak goal uses your best streak during the session.</p></div>}
 {step===2&&<div className="space-y-4"><label className="block">Timer<select className={HW_INPUT} value={timer} onChange={e=>Y(e.target.value as typeof timer)}><option value="regular">Regular practice timer</option><option value="countdown">Countdown — ends automatically</option></select></label>{timer==='countdown'&&<div className="grid grid-cols-2 gap-3"><label>Minutes<input className={HW_INPUT} type="number" min={0} max={1440} value={minutes} onChange={e=>M(Number(e.target.value))}/></label><label>Seconds<input className={HW_INPUT} type="number" min={0} max={59} value={seconds} onChange={e=>X(Number(e.target.value))}/></label></div>}</div>}
 {step===3&&<><label className="block">Surface<select className={HW_INPUT} value={surface} onChange={e=>F(e.target.value)}><option value="">Choose a surface</option>{SURFACES.map(s=><option key={s}>{s}</option>)}</select></label>{surface==='Other'&&<input aria-label="Custom surface" className={HW_INPUT} value={custom} maxLength={100} onChange={e=>U(e.target.value)}/>}<p className="text-xs text-neutral-500">{setup?.name} · {target} {goal==='streak'?'in a row':'landings'} · {timer==='regular'?'Regular timer':`${minutes}m ${seconds}s countdown`}</p></>}
 {error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex justify-between gap-3"><button data-demo-navigation className={HW_BUTTON} disabled={busy} onClick={()=>step?S(step-1):onClose()}>{step?'Back':'Cancel'}</button><button className={HW_BUTTON} disabled={busy} onClick={()=>void next()}>{busy?'Starting…':step===3?'Start session':'Next'}</button></div></div>}</Modal>;
}
