import { PracticeSession, UserProfile, SetupData } from '../domain/types';
import { CATALOG_VERSION } from '../domain/catalog';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'profile_alex',
    displayName: 'Dark Slide Rider',
    instagramHandle: '',
    email: 'rider@darkslide.local',
    preferredTheme: 'system',
    defaultSetupId: 'setup_alex_main',
    savedSetups: [
      {
        id: 'setup_alex_main',
        name: 'Berlinwood Classic 33.6mm',
        deckWidthMm: 33.6,
        isCustomDeckWidth: false,
        wheelMaterial: 'urethane',
        shape: 'popsicle',
        mold: 'medium',
        difficultyRating: 4,
        notes: 'Equipped with Blackriver 3.0 trucks and Oak bowl wheels.',
      },
      {
        id: 'setup_alex_park',
        name: 'FlatFace G15 32mm',
        deckWidthMm: 32,
        isCustomDeckWidth: false,
        wheelMaterial: 'plastic',
        shape: 'boxy',
        mold: 'high',
        difficultyRating: 3,
        notes: 'Crisp snap for fast flatground flips.',
      },
      {
        id: 'setup_alex_custom',
        name: 'Wide Cruiser 36mm',
        deckWidthMm: 36,
        isCustomDeckWidth: false,
        wheelMaterial: 'resin',
        shape: 'cruiser',
        mold: 'low',
        difficultyRating: 5,
        notes: 'Heavy wide board for locked rail grinds.',
      },
    ],
    availableObstacles: ['flatground', 'ledge', 'rail', 'manual_pad'],
    preferredDifficultyRange: [1, 5],
  },
];

export const INITIAL_SESSIONS_ALEX: PracticeSession[] = [
  {
    id: 'session_demo_1',
    trickResult: {
      mode: 'single',
      canonicalName: 'Kickflip to Manual',
      breakdown: [
        'Stance: Regular',
        'Direction: Straight pop',
        'Base: Kickflip (Ollie with toe-side longitudinal flip)',
        'Landing: Balances into Manual (back wheels)',
      ],
      singleTrick: {
        stance: 'regular',
        direction: 'none',
        baseTrickId: 'kickflip',
        bodyVarial: 'none',
        landing: 'manual',
        revert: 'none',
      },
      catalogVersion: CATALOG_VERSION,
    },
    setupSnapshot: {
      id: 'setup_alex_main',
      name: 'Berlinwood Classic 33.6mm',
      deckWidthMm: 33.6,
      wheelMaterial: 'urethane',
      surface: 'Smooth Marble Desk',
      obstacleType: 'manual_pad',
      difficultyRating: 4,
    },
    status: 'success',
    generatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    sessionStartedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    sessionEndedAt: new Date(Date.now() - 86400000 * 3 + 420000).toISOString(),
    attemptCount: 18,
    landingCount: 12,
    firstLandingAttemptNumber: 3,
    activeDurationMs: 420000, // 7 mins
    timerState: { isRunning: false, accumulatedMs: 420000 },
    difficultyRating: 3,
    notes: 'Caught clean bolts into back wheels, held balance for 3 seconds.',
    history: [],
  },
  {
    id: 'session_demo_2',
    trickResult: {
      mode: 'single',
      canonicalName: 'Tre Flip',
      breakdown: [
        'Stance: Regular',
        'Board spin: 360° (Tre Flip)',
        'Base: Tre Flip (360 Backside Shuvit combined with a Kickflip)',
      ],
      singleTrick: {
        stance: 'regular',
        direction: 'none',
        baseTrickId: 'tre_flip',
        bodyVarial: 'none',
        landing: 'normal',
        revert: 'none',
      },
      catalogVersion: CATALOG_VERSION,
    },
    setupSnapshot: {
      id: 'setup_alex_main',
      name: 'Berlinwood Classic 33.6mm',
      deckWidthMm: 33.6,
      wheelMaterial: 'urethane',
      surface: 'Smooth Marble Desk',
      obstacleType: 'flatground',
      difficultyRating: 4,
    },
    status: 'success',
    generatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    sessionStartedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    sessionEndedAt: new Date(Date.now() - 86400000 * 2 + 780000).toISOString(),
    attemptCount: 30,
    landingCount: 19,
    firstLandingAttemptNumber: 4,
    activeDurationMs: 780000, // 13 mins
    timerState: { isRunning: false, accumulatedMs: 780000 },
    difficultyRating: 4,
    notes: 'High scoop rotation, landing right on the hardware.',
    history: [],
  },
  {
    id: 'session_demo_3',
    trickResult: {
      mode: 'combo',
      canonicalName: 'Backside 180 ➔ Fakie Pop Shuvit',
      breakdown: [
        'Step 1: Stance Regular · Backside 180° rotation · Lands in Fakie stance',
        'Step 2: Stance Fakie · Pop Shuvit · Lands clean rollaway',
      ],
      comboSteps: [
        {
          stepNumber: 1,
          parameters: {
            stance: 'regular',
            direction: 'backside',
            baseTrickId: 'ollie',
            bodyVarial: 'none',
            landing: 'normal',
            revert: 'none',
          },
          resolvedName: 'Backside 180',
          landingState: {
            resultStance: 'fakie',
            travelDirection: 'backward',
            boardPosition: 'normal',
          },
          breakdown: 'Stance: Regular · Direction: Backside 180°',
        },
        {
          stepNumber: 2,
          parameters: {
            stance: 'fakie',
            direction: 'none',
            baseTrickId: 'pop_shuvit',
            bodyVarial: 'none',
            landing: 'normal',
            revert: 'none',
          },
          resolvedName: 'Fakie Pop Shuvit',
          landingState: {
            resultStance: 'fakie',
            travelDirection: 'backward',
            boardPosition: 'normal',
          },
          breakdown: 'Stance: Fakie · Base: Pop Shuvit',
        },
      ],
      catalogVersion: CATALOG_VERSION,
    },
    setupSnapshot: {
      id: 'setup_alex_park',
      name: 'FlatFace G15 32mm',
      deckWidthMm: 32,
      wheelMaterial: 'plastic',
      surface: 'Wood Desktop',
      obstacleType: 'flatground',
      difficultyRating: 3,
    },
    status: 'success',
    generatedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    sessionStartedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    sessionEndedAt: new Date(Date.now() - 86400000 * 1.5 + 510000).toISOString(),
    attemptCount: 14,
    landingCount: 8,
    firstLandingAttemptNumber: 2,
    activeDurationMs: 510000,
    timerState: { isRunning: false, accumulatedMs: 510000 },
    difficultyRating: 3,
    notes: 'Fluid continuous roll from BS 180 straight into fakie shuvit.',
    history: [],
  },
  {
    id: 'session_demo_4',
    trickResult: {
      mode: 'obstacle',
      canonicalName: 'Kickflip in to FS 50-50 to FS Revert',
      breakdown: [
        'Obstacle: Ledge',
        'Approach: Frontside',
        'Entry: Kickflip on approach',
        'Grind: 50-50 Grind (both trucks locked)',
        'Exit: Surface FS Revert off ledge',
      ],
      obstacleData: {
        obstacleType: 'ledge',
        approach: 'frontside',
        obstacleTrickId: '50_50',
        entryTrickId: 'kickflip',
        exitTrick: 'revert_fs',
      },
      catalogVersion: CATALOG_VERSION,
    },
    setupSnapshot: {
      id: 'setup_alex_main',
      name: 'Berlinwood Classic 33.6mm',
      deckWidthMm: 33.6,
      wheelMaterial: 'urethane',
      surface: 'Smooth Marble Desk',
      obstacleType: 'ledge',
      difficultyRating: 4,
    },
    status: 'pending',
    generatedAt: new Date(Date.now() - 86400000 * 0.8).toISOString(),
    sessionStartedAt: new Date(Date.now() - 86400000 * 0.8).toISOString(),
    attemptCount: 8,
    landingCount: 2,
    firstLandingAttemptNumber: 5,
    activeDurationMs: 310000,
    timerState: { isRunning: false, accumulatedMs: 310000 },
    difficultyRating: 4,
    notes: 'Working on getting trucks centered consistently without clipping.',
    history: [],
  },
  {
    id: 'session_demo_5',
    trickResult: {
      mode: 'single',
      canonicalName: 'Inward Heelflip',
      breakdown: [
        'Stance: Regular',
        'Base: Inward Heelflip (Backside pop shuvit combined with a heelflip)',
      ],
      singleTrick: {
        stance: 'regular',
        direction: 'none',
        baseTrickId: 'inward_heelflip',
        bodyVarial: 'none',
        landing: 'normal',
        revert: 'none',
      },
      catalogVersion: CATALOG_VERSION,
    },
    setupSnapshot: {
      id: 'setup_alex_park',
      name: 'FlatFace G15 32mm',
      deckWidthMm: 32,
      wheelMaterial: 'plastic',
      surface: 'Wood Desktop',
      obstacleType: 'flatground',
      difficultyRating: 4,
    },
    status: 'failed',
    generatedAt: new Date(Date.now() - 86400000 * 0.2).toISOString(),
    sessionStartedAt: new Date(Date.now() - 86400000 * 0.2).toISOString(),
    sessionEndedAt: new Date(Date.now() - 86400000 * 0.2 + 960000).toISOString(),
    attemptCount: 25,
    landingCount: 0,
    activeDurationMs: 960000,
    timerState: { isRunning: false, accumulatedMs: 960000 },
    difficultyRating: 5,
    notes: 'Board kept over-flipping. Will revisit in next session.',
    history: [],
  },
];
