import React,{useCallback,useEffect,useRef,useState,useMemo} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {Check,ArrowRight,Layers,Pause,Play,Volume2,VolumeX,Music2,SkipForward,Sparkles,Trophy} from 'lucide-react';
import {useApp} from '../../context/AppContext';
import {DeckMode,DeckGameLink,GAME_DECKS,deckPickerSummary,freshDeckGame,deckRun,cardBudget,recordDeckAttempt,currentWildcard,cardPassed,cardTarget,activeDeckTrick,deckModeLabel,WILDCARD_LABELS} from '../../domain/deckGame';
import {createPracticeSession} from '../../domain/practiceActions';
import {closePractice} from '../../domain/sessionPlan';
import {pauseTimer,startTimer,calculateActiveDurationMs,formatDurationMs} from '../../domain/timer';
import {PracticeSession,SetupData} from '../../domain/types';
import {SessionStartWizard} from '../generator/SessionStartWizard';
import {Modal} from '../common/Modal';
import {CardStack,DrawnTrickCard,DeckPicker,ShufflingDeck} from './PlayingCards';
import {playDeckSound,setDeckSoundEnabled,setDeckMusicEnabled,currentDeckMusic,nextDeckMusic,unlockDeckSound} from './deckSounds';
const CARD='rounded-2xl border border-neutral-300 dark:border-neutral-800 bg-white dark:bg-[#08090b] p-5 sm:p-6';
const BUTTON='min-h-12 rounded-xl bg-[#D4A72C] text-black px-5 py-3 font-semibold cursor-pointer hover:bg-[#e1b841] disabled:opacity-50 disabled:cursor-not-allowed';
export function DeckGamesPage(){
 const {sessions,profile,startDeckCard,updateSession,setActiveTab,currentSession}=useApp();
 const picker=useMemo(()=>deckPickerSummary(sessions),[sessions]);
 const resumable=picker.resumable;
 const [gameId,setGameId]=useState<string|null>(()=>new URLSearchParams(location.search).get('game') ||null),[mode,setMode]=useState<DeckMode>('normal'),[draft,setDraft]=useState<{game:DeckGameLink;session:PracticeSession;defaults?:{setupId:string;surface:string}}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[quit,setQuit]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const sync=()=>{const id=new URLSearchParams(location.search).get('game');if(id)setGameId(id);};window.addEventListener('app-route-change',sync);window.addEventListener('popstate',sync);return()=>{window.removeEventListener('app-route-change',sync);window.removeEventListener('popstate',sync);};},[]);
 const saving=useRef(false);
 const [prepared,setPrepared]=useState<{game:DeckGameLink;setup:SetupData;surface:string}|null>(null);
 const [musicEnabled,setMusicEnabled]=useState(true);
 const [musicName,setMusicName]=useState(()=>currentDeckMusic().name);
 const [soundEnabled,setSoundEnabled]=useState(true),[shaking,setShaking]=useState(false);
 const [departingCard,setDepartingCard]=useState<string|null>(null);
 const [deckPage,setDeckPage]=useState(1);
 const [pageDirection,setPageDirection]=useState(1);
 const reducePageMotion=useReducedMotion();
 const changeDeckPage=(page:number)=>{if(page===deckPage||page<1||page>Math.ceil(GAME_DECKS.length/8))return;setPageDirection(page>deckPage?1:-1);setDeckPage(page);};
 const deckPageCount=Math.ceil(GAME_DECKS.length/8);
 const visibleDecks=GAME_DECKS.slice((deckPage-1)*8,deckPage*8);
 const [selectedDeck,setSelectedDeck]=useState<string|null>(null);
 const [revealedCard,setRevealedCard]=useState<string|null>(null);
 const requestedRun=gameId?picker.runs.find(r=>r.game.gameId===gameId)??null:null;
 const run=requestedRun&&(requestedRun.done||requestedRun.game.gameId===resumable?.game.gameId)?requestedRun:null,active=run?.latest,deck=GAME_DECKS.find(d=>d.id===run?.game.deckId);
 useEffect(()=>{setDeckMusicEnabled(musicEnabled);return()=>setDeckMusicEnabled(false);},[musicEnabled]);
 useEffect(()=>{setDeckSoundEnabled(soundEnabled);return()=>setDeckSoundEnabled(true);},[soundEnabled]);
 useEffect(()=>{if(active&&!active.sessionEndedAt&&!run?.done)playDeckSound('draw');},[active?.id]);
 const returnToDecks=()=>{setGameId(null);const url=new URL(location.href);url.searchParams.delete('game');history.replaceState(history.state,'',url.pathname+url.search+url.hash);};
 const drawing=!!active&&!active.sessionEndedAt&&revealedCard!==active.id;
 const revealCard=useCallback(()=>{if(active)setRevealedCard(active.id);},[active?.id]);
 useEffect(()=>{if(!active?.timerState.isRunning||active.sessionEndedAt)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[active?.id,active?.timerState.isRunning,active?.sessionEndedAt]);
 const perform=async(action:()=>Promise<void>)=>{if(saving.current)return;saving.current=true;setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.');}finally{setShaking(false);setDepartingCard(null);saving.current=false;setBusy(false);setNow(Date.now());}};
 const prepare=(id:string,chosenMode:DeckMode=mode,previous?:PracticeSession)=>{
  const d=GAME_DECKS.find(d=>d.id===id)!;
  const game=freshDeckGame(id,chosenMode);
  const setup=profile?.savedSetups.find(s=>s.id===previous?.setupSnapshot.id)||profile?.savedSetups[0]||{id:'unset',name:'Choose a setup',deckWidthMm:34,wheelMaterial:'unknown' as const};
  const session=createPracticeSession(d.cards.find(c=>c.id===game.order[0])!.trick,setup);session.goal={type:'landings',target:1};session.practiceTimer={type:'regular'};if(previous?.practiceSurface)session.practiceSurface=previous.practiceSurface;
  setError('');setDraft({game,session,...(previous?{defaults:{setupId:previous.setupSnapshot.id,surface:previous.practiceSurface||''}}:{})});
 };
 const next=()=>void perform(async()=>{if(!run||run.done||!active?.sessionEndedAt)return;await startDeckCard({...run.game,cardIndex:run.game.cardIndex+1,lettersBefore:run.letters},active.setupSnapshot,active.practiceSurface!);});
 const attempt=(landed:boolean)=>void perform(async()=>{
  if(!active||!run||drawing)return;const recorded=recordDeckAttempt(active,landed);
  if(!landed&&run.game.mode!=='skate'){playDeckSound('miss');setShaking(true);await new Promise<void>(resolve=>window.setTimeout(resolve,300));setShaking(false);}
  if(recorded.sessionEndedAt){playDeckSound('discard');setDepartingCard(active.id);if(!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)await new Promise<void>(resolve=>window.setTimeout(resolve,450));}
  await updateSession(recorded);
  const updated=deckRun([...sessions.filter(s=>s.id!==recorded.id),recorded],run.game.gameId)!;
  if(run.game.mode==='skate'&&updated.letters>run.letters)playDeckSound('letter');
  if(updated.done&&!updated.conflict&&!updated.game.endedEarly){const cleared=updated.dealt===updated.total&&(updated.game.mode==='skate'?updated.letters<5:updated.landed===updated.total);playDeckSound(cleared?'victory':'failure');}
  if(recorded.sessionEndedAt&&!updated.done)await startDeckCard({...run.game,cardIndex:run.game.cardIndex+1,lettersBefore:updated.letters},active.setupSnapshot,active.practiceSurface!);
 });
 const togglePause=()=>void perform(async()=>{if(!active||active.sessionEndedAt)return;const timerState=active.timerState.isRunning?pauseTimer(active.timerState):startTimer(active.timerState);await updateSession({...active,timerState,activeDurationMs:calculateActiveDurationMs(timerState),parkedAt:timerState.isRunning?undefined:new Date().toISOString()});});
 const pagination=<nav aria-label="Deck pages" className="flex flex-wrap items-center justify-end gap-2"><button type="button" disabled={deckPage===1} onClick={()=>changeDeckPage(deckPage-1)} className="min-h-11 px-4 rounded-lg border border-white/20 text-sm cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed">Previous</button>{Array.from({length:deckPageCount},(_,i)=>i+1).map(page=><button type="button" key={page} aria-label={`Deck page ${page}`} aria-current={deckPage===page?'page':undefined} onClick={()=>changeDeckPage(page)} className={`min-h-11 min-w-11 rounded-lg border text-sm font-semibold cursor-pointer ${deckPage===page?'bg-[#D4A72C] text-black border-[#D4A72C]':'border-white/20 hover:border-[#D4A72C]'}`}>{page}</button>)}<button type="button" disabled={deckPage===deckPageCount} onClick={()=>changeDeckPage(deckPage+1)} className="min-h-11 px-4 rounded-lg border border-white/20 text-sm cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed">Next</button></nav>;
 return <div className="space-y-4" onPointerDownCapture={unlockDeckSound} onKeyDownCapture={unlockDeckSound}><header className="space-y-3"><p className="flex items-center gap-2 text-xs uppercase tracking-widest font-semibold text-[#8A6500] dark:text-[#D4A72C]"><Layers size={16}/>Shuffle. Attempt. Progress.</p><h1 className="text-3xl sm:text-4xl font-bold">Session Decks</h1><p className="text-sm sm:text-base text-neutral-500 leading-7">A fixed set of tricks. A fresh shuffle. One card at a time.</p><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-y-1"><button type="button" aria-pressed={soundEnabled} aria-label={soundEnabled?'Mute game sounds':'Enable game sounds'} title={soundEnabled?'Mute game sounds':'Enable game sounds'} className="min-h-11 inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#D4A72C] cursor-pointer" onClick={()=>{const next=!soundEnabled;setDeckSoundEnabled(next);setSoundEnabled(next);if(next){unlockDeckSound();playDeckSound('fan');}}}>{soundEnabled?<Volume2 size={17}/>:<VolumeX size={17}/>}Sound {soundEnabled?'on':'off'}</button><button type="button" aria-pressed={musicEnabled} aria-label={musicEnabled?'Mute background music':'Enable background music'} className="ml-4 min-h-11 inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#D4A72C] cursor-pointer" onClick={()=>{const next=!musicEnabled;setDeckMusicEnabled(next);setMusicEnabled(next);if(next)unlockDeckSound();}}><Music2 size={17}/>Music {musicEnabled?'on':'off'}</button><button type="button" disabled={!musicEnabled} onClick={()=>{unlockDeckSound();setMusicName(nextDeckMusic().name);}} aria-label="Next music" title="Shuffle to the next track" className="ml-4 min-h-11 inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-[#D4A72C] cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"><SkipForward size={17}/>Next music</button><span className="deck-music-title" aria-live="polite">{musicEnabled?musicName:'Music paused'}</span></div>{!prepared&&(!run||run.done)&&pagination}</div></header>
 {draft&&<SessionStartWizard session={draft.session} gameDefaults={draft.defaults} gameMode={draft.game.mode} onBack={()=>{if(busy)return;setMode(draft.game.mode);setSelectedDeck(draft.game.deckId);setDraft(null);}} gameSetup={`${GAME_DECKS.find(d=>d.id===draft.game.deckId)?.name} · ${deckModeLabel(draft.game.mode)}`} onClose={()=>{if(!busy)setDraft(null);}} onStart={async configured=>{if(saving.current)return;setGameId(null);setPrepared({game:draft.game,setup:configured.setupSnapshot,surface:configured.practiceSurface!});setDraft(null);}}/>}
 <Modal isOpen={!!selectedDeck} onClose={()=>setSelectedDeck(null)} title={`${GAME_DECKS.find(d=>d.id===selectedDeck)?.name||'Deck'} · Choose your rules`}>
<div className="deck-mode-dialog">
 <div className="deck-mode-intro"><span className="deck-mode-eyebrow">CHOOSE YOUR RULES</span><h3>{GAME_DECKS.find(d=>d.id===selectedDeck)?.name||'Session Deck'}</h3><p>One shuffled deck. Choose how you want to play.</p><span className="deck-mode-deck-badge"><Layers size={14} aria-hidden="true"/>{GAME_DECKS.find(d=>d.id===selectedDeck)?.cards.length||8} cards · {deckModeLabel(mode)}</span></div>
 <div className="deck-mode-options">{([{id:'normal',title:'Normal',description:'Five tries per card. Land it once to pass. Keep going through all eight cards.',tag:'5 TRIES / CARD',Icon:Layers},{id:'wildcard',title:'Wildcard',description:'Normal rules with surprise jokers.',tag:'3 SURPRISE JOKERS',Icon:Sparkles},{id:'skate',title:'Game of SKATE',description:'A missed card earns a letter. The game ends at SKATE or when the deck runs out.',tag:'LAST LETTER: 2 TRIES',Icon:Trophy}] as const).map(m=><button type="button" key={m.id} aria-pressed={mode===m.id} onClick={()=>setMode(m.id)} className={`deck-mode-option ${mode===m.id?'is-selected':''}`}>
  <div className="deck-mode-option-heading"><span className="deck-mode-medallion"><m.Icon size={26} aria-hidden="true"/><span>{m.id==='skate'?'SKATE':m.id.toUpperCase()}</span></span><span className="deck-mode-heading-copy"><span className="deck-mode-selection">{mode===m.id?'SELECTED':'CHOOSE MODE'}</span><strong>{m.title}</strong></span><span className="deck-mode-check" aria-hidden="true">{mode===m.id?<Check size={13}/>:null}</span></div>
  <span className="deck-mode-rule">{m.description}</span><span className="deck-mode-rule-tag">{m.tag}</span>
 </button>)}</div>
 <button type="button" className={`${BUTTON} deck-mode-continue`} onClick={()=>{if(selectedDeck){prepare(selectedDeck);setSelectedDeck(null);}}}>Continue to session setup<ArrowRight size={17} aria-hidden="true"/></button>
</div></Modal>
 {error&&<p role="alert" className="rounded-xl border border-rose-500/30 p-4 text-sm text-rose-600 dark:text-rose-400">{error}</p>}
 {prepared?<section className={CARD}><ShufflingDeck deckId={prepared.game.deckId} key={prepared.game.gameId} name={GAME_DECKS.find(d=>d.id===prepared.game.deckId)?.name||'Session Deck'} disabled={busy} onDraw={()=>void perform(async()=>{await startDeckCard({...prepared.game,gameStartedAt:new Date().toISOString()},prepared.setup,prepared.surface);setGameId(prepared.game.gameId);setPrepared(null);})}/><button type="button" disabled={busy} className="min-h-11 text-sm text-neutral-500 underline underline-offset-4 cursor-pointer" onClick={()=>setPrepared(null)}>Return to deck picker</button></section>:!run||run.done?<>
 <section className="deck-picker-table" aria-label="Choose a session deck"><div className="overflow-hidden"><AnimatePresence initial={false} mode="wait" custom={pageDirection}><motion.div key={deckPage} custom={pageDirection} variants={{enter:(direction:number)=>({x:reducePageMotion?0:direction*70,opacity:reducePageMotion?1:0}),visible:{x:0,opacity:1},exit:(direction:number)=>({x:reducePageMotion?0:-direction*70,opacity:reducePageMotion?1:0,pointerEvents:'none' as const})}} initial="enter" animate="visible" exit="exit" transition={{duration:reducePageMotion?0:.22,ease:'easeInOut'}} className="grid grid-cols-2 lg:grid-cols-4 gap-x-4 gap-y-6">{visibleDecks.map(d=><DeckPicker key={d.id} deckId={d.id} name={d.name} count={d.cards.length} normalStatus={picker.statuses[d.id].normal} skateStatus={picker.statuses[d.id].skate} wildcardStatus={picker.statuses[d.id].wildcard} disabled={busy} onChoose={()=>{setMode('normal');setSelectedDeck(d.id);}} resumes={(resumable?.game.deckId===d.id?[resumable]:[]).map(r=>({id:r.game.gameId,label:`Resume ${deckModeLabel(r.game.mode)} · ${r.landed}/${r.total}`}))} onResume={id=>setGameId(id)}/>)}</motion.div></AnimatePresence></div><p className="deck-picker-table-note">{currentSession?.sessionStartedAt&&!currentSession.sessionEndedAt?'Starting a deck will park your current session. ':''}Your setup and surface are configured once before play. Starting a new deck replaces the previous saved game; recorded stats stay in your history.</p></section></>:
 <section className={`${CARD} session-game-panel space-y-4`}><div className="session-deck-scoreboard session-game-header"><div className="session-deck-heading"><p className="session-deck-eyebrow">SESSION DECKS</p><h2>{deckModeLabel(run.game.mode)}</h2><p className="session-deck-name">{deck?.name}</p><p className="session-deck-equipment">{active?.setupSnapshot.name} · {active?.practiceSurface}</p></div><div className={`session-deck-score ${run.game.mode==='skate'?'session-skate-score':''}`}>{run.game.mode==='skate'?<><p className="session-deck-eyebrow">YOUR LETTERS</p><div className="session-skate-letters" aria-label={`${run.letters} of 5 SKATE letters`}>{'SKATE'.split('').map((letter,i)=><span key={letter} className={i<run.letters?'earned-letter':''}>{letter}</span>)}</div><p className="session-deck-score-caption">{run.landed} landed · {run.dealt}/{run.total} dealt</p></>:<><p className="session-deck-eyebrow">CARDS LANDED</p><p className="session-normal-score"><strong className={run.landed>0?'session-normal-earned':undefined}>{run.landed}</strong><span> / {run.total}</span></p><p className="session-deck-score-caption">{run.dealt}/{run.total} cards dealt</p></>}</div></div>
 {active&&<div className="space-y-3"><div className="flex justify-between gap-3 text-xs text-neutral-500"><span>Card {run.game.cardIndex+1} of {run.total}</span><span>{formatDurationMs(calculateActiveDurationMs(active.timerState,now))}</span></div><div className="playing-table"><CardStack deckId={run.game.deckId} count={run.total-run.dealt} label="Draw pile"/><DrawnTrickCard deckId={run.game.deckId} shaking={shaking} departing={departingCard===active.id} key={active.id} name={activeDeckTrick(active).canonicalName} wildcard={currentWildcard(run.game)} targetLabel={currentWildcard(run.game)?WILDCARD_LABELS[currentWildcard(run.game)!]:undefined} number={run.game.cardIndex+1} total={run.total} status={active.sessionEndedAt?(cardPassed(active)?'passed':'missed'):'live'} onReveal={revealCard}/><CardStack deckId={run.game.deckId} played count={run.dealt-(active.sessionEndedAt?0:1)} label="Played pile"/></div><p className="text-sm text-neutral-500">{active.sessionEndedAt?cardPassed(active)?'Passed — target reached.':'Card missed.':`${cardBudget(run.game)-active.attemptCount} ${cardBudget(run.game)-active.attemptCount===1?'try':'tries'} left · ${active.landingCount}/${cardTarget(run.game)} landings${currentWildcard(run.game)==='opposite_stance'?' · one in each stance':''}`}</p>{run.game.mode==='skate'&&run.letters===4&&!active.sessionEndedAt&&<p className="text-sm text-[#8A6500] dark:text-[#D4A72C]">Final-letter rule: two tries on this card before E.</p>}
 {active.sessionEndedAt&&!busy?<button disabled={busy} className={`${BUTTON} w-full flex items-center justify-center gap-2`} onClick={next}>Draw next card <ArrowRight size={16}/></button>:<><div className="grid grid-cols-2 gap-3"><button type="button" className="min-h-14 rounded-xl border border-neutral-300 dark:border-neutral-700 text-sm font-semibold cursor-pointer disabled:opacity-40" disabled={busy||drawing||!!active.sessionEndedAt||!active.timerState.isRunning} onClick={()=>attempt(false)}>Missed attempt</button><button type="button" className={`${BUTTON} flex items-center justify-center gap-2`} disabled={busy||drawing||!!active.sessionEndedAt||!active.timerState.isRunning} onClick={()=>attempt(true)}><Check size={18}/>Landed it</button></div><button type="button" disabled={busy||drawing} className="min-h-11 text-sm underline underline-offset-4 cursor-pointer flex items-center gap-2" onClick={togglePause}>{active.timerState.isRunning?<><Pause size={14}/>Pause game</>:<><Play size={14}/>Resume game</>}</button></>}
 <details><summary className="text-sm cursor-pointer text-neutral-500">How to record tries</summary><p className="text-xs leading-6 mt-2 text-neutral-500">Tap one button per try. Landed it records both an attempt and a landing. A card ends when its landing target is reached or its attempt budget runs out. Wildcards show their rule on the face. Opposite-stance cards switch after your first landing; both landings share the same five tries. Completed cards are saved to your history.</p></details><button type="button" disabled={busy} className="min-h-11 text-xs underline underline-offset-4 text-neutral-500 cursor-pointer" onClick={()=>setQuit(true)}>End this game early</button><button type="button" className="min-h-11 text-xs underline underline-offset-4 text-neutral-500 cursor-pointer ml-4" disabled={busy} onClick={()=>void perform(async()=>{if(!active.sessionEndedAt&&active.timerState.isRunning){const timerState=pauseTimer(active.timerState);await updateSession({...active,timerState,activeDurationMs:calculateActiveDurationMs(timerState),parkedAt:new Date().toISOString()});}setGameId(null);})}>Save & return to decks</button></div>}
</section>}
 <Modal isOpen={!!run?.done} onClose={returnToDecks} titleClassName="text-xl sm:text-2xl" title={run?.conflict?'Conflicting records':run?.game.endedEarly?'Game ended early':run&&run.dealt===run.total&&(run.game.mode==='skate'?run.letters<5:run.landed===run.total)?'Deck won!':'Deck failed!'}>{run&&<div className="space-y-5"><p className="text-xs uppercase tracking-widest text-[#D4A72C]">{deck?.name} · {deckModeLabel(run.game.mode)}</p><h2 className="text-3xl font-bold">{run.landed}/{run.total} cards landed</h2>{!run.conflict&&!run.game.endedEarly&&(run.suddenDeath||run.letters===5)&&<p className="text-sm text-neutral-500">{run.suddenDeath?'You missed the Sudden Death card.':'You collected all five letters: SKATE.'}</p>}<div className="grid grid-cols-2 gap-3">{[['Missed cards',run.failed],['Undealt cards',run.total-run.dealt],['Attempts',run.attempts],['Active time',formatDurationMs(run.time)]].map(([label,value])=><div key={label} className="rounded-xl border border-neutral-300 dark:border-neutral-800 p-4"><p className="text-xs text-neutral-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div><p className="text-sm text-neutral-500">Your recorded attempts and landings are saved in your session history.</p><div className="grid sm:grid-cols-2 gap-3"><button type="button" disabled={busy} className={`${BUTTON} w-full`} onClick={()=>{if(!deck)return;const previous=run.latest,chosenMode=run.game.mode;returnToDecks();setMode(chosenMode);setRevealedCard(null);prepare(deck.id,chosenMode,previous);}}>Re-run deck</button><button type="button" className="min-h-12 rounded-xl border border-neutral-300 dark:border-neutral-700 px-5 py-3 font-semibold cursor-pointer hover:border-[#D4A72C]" onClick={returnToDecks}>Return to deck picker</button></div></div>}</Modal>
 <Modal isOpen={quit} onClose={()=>{if(!busy)setQuit(false);}} title="End the game early?"><p className="text-sm leading-7 text-neutral-500">Played cards stay in your history. Undealt cards will not count as failures. You can start a fresh shuffled deck afterward.</p><div className="flex gap-3 mt-5"><button className={BUTTON} disabled={busy} onClick={()=>void perform(async()=>{if(!active)return;const ended=active.sessionEndedAt?active:closePractice(active,false,active.difficultyRating,active.notes);await updateSession({...ended,deckGame:{...active.deckGame!,endedEarly:true}});setQuit(false);})}>End game</button><button disabled={busy} className="min-h-12 px-4 cursor-pointer" onClick={()=>setQuit(false)}>Keep playing</button></div></Modal>
 </div>;
}
