import {navigate} from '../../domain/routes';
import React from 'react';
import {allDeckRuns,GAME_DECKS,cardPassed,deckModeLabel} from '../../domain/deckGame';
import {PracticeSession} from '../../domain/types';
import {formatDurationMs} from '../../domain/timer';
export function DeckGameStats({sessions}:{sessions:PracticeSession[]}){
 const runs=allDeckRuns(sessions);if(!runs.length)return null;
 const cards=runs.flatMap(r=>r.cards),attempts=cards.reduce((n,s)=>n+s.attemptCount,0),landings=cards.reduce((n,s)=>n+s.landingCount,0),passed=cards.filter(s=>s.sessionEndedAt&&cardPassed(s)).length;
 return <details className="ds-surface rounded-2xl border border-neutral-300 dark:border-neutral-800 bg-white dark:bg-neutral-950 p-5"><summary className="font-semibold cursor-pointer">Practice Deck results · {runs.length} games</summary><div className="mt-5 space-y-5"><p className="text-xs text-neutral-500">Uses complete recorded deck runs across your account. Shared dashboard filters do not alter these game summaries. Card attempts also contribute to the regular dashboard charts and setup comparisons.</p><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Cards passed',String(passed)],['Attempts',String(attempts)],['Landing rate',attempts?`${Math.round(landings/attempts*100)}%`:'—'],['Decks finished',String(runs.filter(r=>r.done&&!r.game.endedEarly&&!r.conflict&&r.dealt===r.total).length)]].map(([label,value])=><div key={label}><p className="text-xs text-neutral-500">{label}</p><p className="text-2xl font-semibold mt-2">{value}</p></div>)}</div><div className="divide-y divide-neutral-300 dark:divide-neutral-800">{runs.slice(0,20).map(r=><article key={r.game.gameId} className="py-4 space-y-2"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold text-sm">{GAME_DECKS.find(d=>d.id===r.game.deckId)?.name} · {deckModeLabel(r.game.mode)}</h3><span className="text-sm text-[#8A6500] dark:text-[#D4A72C]">{r.landed}/{r.total} cards passed</span></div><p className="text-xs text-neutral-500 leading-6">{new Date(r.game.gameStartedAt).toLocaleDateString()} · {r.conflict?'Conflicting records':r.game.endedEarly?'Ended early':r.suddenDeath?'Sudden Death':r.done?'Finished':'In progress'} · {r.failed} missed · {r.total-r.dealt} undealt · {r.attempts} attempts · {formatDurationMs(r.time)}{r.game.mode==='skate'?` · ${'SKATE'.slice(0,r.letters)||'No letters'}`:''}</p><button type="button" onClick={()=>navigate('/deck-games?game='+encodeURIComponent(r.game.gameId))} className="min-h-11 text-xs underline underline-offset-4 cursor-pointer">View game</button></article>)}</div>{runs.length>20&&<p className="text-xs text-neutral-500">Showing the latest 20 games. All card records remain in Session History.</p>}</div></details>;
}
