import React,{useState,useEffect} from 'react';
import {Modal} from './Modal';
export const BETA_VERSION='0.1.0-beta.1';
export function BetaTools(){
 const [open,setOpen]=useState(false),[save,setSave]=useState({state:'',message:''}),[online,setOnline]=useState(typeof navigator==='undefined'||navigator.onLine),[steps,setSteps]=useState(''),[expected,setExpected]=useState(''),[actual,setActual]=useState(''),[copied,setCopied]=useState(false);
 useEffect(()=>{const changed=(e:Event)=>setSave((e as CustomEvent).detail),connected=()=>setOnline(navigator.onLine);window.addEventListener('cloud-save-status',changed);window.addEventListener('online',connected);window.addEventListener('offline',connected);return()=>{window.removeEventListener('cloud-save-status',changed);window.removeEventListener('online',connected);window.removeEventListener('offline',connected);};},[]);
 useEffect(()=>{const protect=(event:BeforeUnloadEvent)=>{if(save.state==='saving'){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[save.state]);
 const input='w-full rounded-lg border border-neutral-300 dark:border-neutral-700 bg-transparent p-3 mt-1 text-sm';
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('open-beta-report',show);return()=>window.removeEventListener('open-beta-report',show);},[]);
 return <><div className={save.state||!online?"flex justify-end mb-3 text-xs":"hidden"}><span role="status" aria-live="polite" className={save.state==='error'||!online?'text-rose-600 dark:text-rose-400':'text-neutral-500'}>{!online?'Offline · reconnect before saving':save.state==='saving'?'Saving…':save.state==='saved'?'Saved to your account':save.state==='error'?save.message:''}</span></div><Modal isOpen={open} onClose={()=>setOpen(false)} title="Report a beta issue"><div className="space-y-4"><p className="text-sm text-neutral-500">Copy your report and send it to @ktnk.fb. Include an optional screenshot with personal information removed. Never include passwords.</p><label className="block text-sm">Steps to reproduce<textarea className={input} rows={3} value={steps} onChange={e=>setSteps(e.target.value)}/></label><label className="block text-sm">What did you expect?<textarea className={input} rows={2} value={expected} onChange={e=>setExpected(e.target.value)}/></label><label className="block text-sm">What happened?<textarea className={input} rows={2} value={actual} onChange={e=>setActual(e.target.value)}/></label><button type="button" className="cursor-pointer rounded-lg bg-[#D4A72C] text-black px-4 py-3" onClick={async()=>{const report=`DARK SLIDE ${BETA_VERSION}\nPage: ${location.pathname}${location.hash}\nBrowser: ${navigator.userAgent}\nSteps: ${steps}\nExpected: ${expected}\nActual: ${actual}`;try{await navigator.clipboard.writeText(report);setCopied(true);}catch{setCopied(false);alert('Clipboard unavailable. Copy the text you entered manually.');}}}>{copied?'Report copied':'Copy report'}</button><a className="inline-block ml-3 cursor-pointer underline" href="https://www.instagram.com/ktnk.fb/" target="_blank" rel="noopener noreferrer">Contact @ktnk.fb</a></div></Modal></>;
}
