import {sessionRecap} from '../../domain/sessionRecap';
import {formatDurationMs} from '../../domain/timer';
import React,{useEffect,useState} from 'react';
import {Sparkles,ArrowRight,RotateCcw,CheckCircle2,Target,Unlock} from 'lucide-react';
import {Modal} from './Modal';
import {SessionReward} from '../../domain/riderProgression';
import {PracticeSession} from '../../domain/types';
import {PracticeTarget,nextSteps,personalWins,goalLabel} from '../../domain/practiceTargets';

export function RewardBreakdown({reward}: {reward:SessionReward}) {
 return <section className="space-y-4" aria-label="Practice rewards"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-[#8A6500] dark:text-[#D4A72C]">Your session recap</p><h3 className="mt-2 text-lg font-semibold break-words">{reward.trickName}</h3></div>{reward.xp>0&&<p className="shrink-0 text-2xl font-bold text-[#8A6500] dark:text-[#D4A72C]">+{reward.xp}<span className="block text-right text-xs font-medium">XP</span></p>}</div>{reward.rewards.length>0&&<ul className="divide-y divide-neutral-200 dark:divide-neutral-800">{reward.rewards.map(item=><li key={item.id} className="flex items-center justify-between gap-4 py-3 text-sm"><span>{item.label}</span><span className="shrink-0 font-semibold text-[#8A6500] dark:text-[#D4A72C]">+{item.xp}</span></li>)}</ul>}{reward.levelAfter>reward.levelBefore&&<p role="status" className="flex items-center gap-2 rounded-xl border border-[#D4A72C]/40 bg-[#D4A72C]/10 p-4 font-semibold"><Sparkles size={20} className="shrink-0 text-[#D4A72C]"/>Level up! You reached Level {reward.levelAfter}.</p>}</section>;
}
export function ProgressionReward({reward,records,onClose,onProgress,onSaveTarget,onRetry}: {reward:SessionReward|null;records:PracticeSession[];onClose:()=>void;onProgress:()=>void;onSaveTarget:(target:PracticeTarget)=>Promise<void>;onRetry:(session:PracticeSession)=>Promise<void>}) {
 const [chosen,setChosen]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[alternatives,setAlternatives]=useState(false);
 useEffect(()=>{setChosen(0);setError('');setAlternatives(false);},[reward?.sessionId]);
 const recap=reward?sessionRecap(records,reward.sessionId):null;
 const choices=reward?nextSteps(records,reward.sessionId):[];
 const session=recap?.session;
 const action=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Could not continue. Please retry.');}finally{setBusy(false);}};
 const stats=recap&&session?[
  ['Landings',`${session.landingCount} / ${session.attemptCount}`],
  ['Landing rate',recap.landingRate===null?'—':`${Math.round(recap.landingRate*100)}%`],
  ['Active time',formatDurationMs(session.activeDurationMs)],
  ['Best streak',`${recap.bestStreak} in a row`]
 ]:[];
 return <Modal isOpen={!!reward} onClose={()=>{if(!busy)onClose();}} title="Session recap" titleClassName="text-xl sm:text-2xl">{reward&&<div className="space-y-5">
  <header className="space-y-3"><span className="inline-flex items-center gap-2 rounded-lg border border-[#D4A72C]/40 bg-[#D4A72C]/10 px-3 py-2 text-sm font-semibold text-[#8A6500] dark:text-[#D4A72C]">{recap?.reached?<CheckCircle2 size={18}/>:<Target size={18}/>} {recap?.reached?'Goal reached':'Goal not reached'}</span><h2 className="text-xl sm:text-2xl font-semibold break-words">{reward.trickName}</h2><p className="text-sm text-neutral-600 dark:text-neutral-400">{session?.goal?goalLabel(session.goal):'Recorded practice'} · Session saved</p></header>
  <dl className="grid grid-cols-2 gap-3">{stats.map(([label,value])=><div key={label} className="rounded-xl border border-neutral-300 dark:border-neutral-700 p-4"><dt className="text-xs text-neutral-600 dark:text-neutral-400">{label}</dt><dd className="mt-2 text-lg sm:text-xl font-semibold">{value}</dd></div>)}</dl>
  {recap&&<p className="text-sm text-neutral-600 dark:text-neutral-400">First landing: {recap.firstAttempt===null?'not recorded':`attempt ${recap.firstAttempt}`}{recap.firstTime!==null?` · ${formatDurationMs(recap.firstTime)} active time`:''}</p>}
  {recap&&recap.wins.length>0?<section className="rounded-xl border border-[#D4A72C]/40 bg-[#D4A72C]/5 p-4 space-y-3"><h3 className="text-xs uppercase tracking-widest font-semibold text-[#8A6500] dark:text-[#D4A72C]">{recap.reached?'Your breakthrough':'Progress beyond the goal'}</h3><p className="text-lg font-semibold leading-7">{recap.wins[0]}</p>{recap.wins.length>1&&<details><summary className="cursor-pointer text-sm">More improvements</summary>{recap.wins.slice(1).map(win=><p key={win} className="mt-3 text-sm leading-6">{win}</p>)}</details>}</section>:<p className="text-sm leading-6 text-neutral-600 dark:text-neutral-400">No new personal best this time. Your recorded landings still build your progress.</p>}
  {!!recap?.unlocked.length&&<section className="rounded-xl border border-[#D4A72C]/40 p-4 space-y-2"><h3 className="flex items-center gap-2 font-semibold"><Unlock size={18} className="text-[#D4A72C]"/>New tricks unlocked</h3><p className="text-sm leading-6">{recap.unlocked.map(n=>n.name).join(' · ')}</p><p className="text-xs text-neutral-500">Your prerequisites reached 10 lands. Mastery remains at 100.</p></section>}
  {choices[chosen]&&<section className="rounded-xl border border-neutral-300 dark:border-neutral-700 p-4 space-y-3"><p className="text-xs text-[#8A6500] dark:text-[#D4A72C] uppercase tracking-widest">One next step</p><h3 className="font-semibold">{choices[chosen].target.title}</h3><p className="text-sm text-neutral-600 dark:text-neutral-400 leading-6">{choices[chosen].target.reason}</p><button type="button" disabled={busy} className="min-h-11 text-sm underline underline-offset-4 cursor-pointer" aria-expanded={alternatives} onClick={()=>setAlternatives(v=>!v)}>Choose another goal</button>{alternatives&&<fieldset disabled={busy} className="space-y-3"><legend className="sr-only">Your next target</legend>{choices.map((choice,index)=><label key={choice.label} className={`flex gap-3 rounded-xl border p-3 cursor-pointer ${chosen===index?'border-[#D4A72C] bg-[#D4A72C]/5':'border-neutral-300 dark:border-neutral-700'}`}><input type="radio" name="next-target" className="mt-1 accent-[#D4A72C]" checked={chosen===index} onChange={()=>setChosen(index)}/><span><strong className="block text-sm">{choice.label}</strong><span className="block mt-1 text-xs leading-5 break-words">{choice.target.title}</span></span></label>)}</fieldset>}</section>}
  {error&&<p role="alert" className="text-sm text-rose-600 dark:text-rose-400">{error}</p>}
  <button type="button" disabled={busy||!choices[chosen]} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#D4A72C] px-4 py-3 text-black font-semibold cursor-pointer hover:bg-[#e1b841] disabled:opacity-50" onClick={()=>void action(async()=>{await onSaveTarget(choices[chosen].target);onProgress();})}>{busy?'Working…':'Save next target · return Home'}<ArrowRight size={16}/></button>
  <div className="grid sm:grid-cols-2 gap-3"><button type="button" disabled={busy||!session} onClick={()=>void action(async()=>{await onRetry(session!);onClose();})} className="flex min-h-12 items-center justify-center gap-2 rounded-lg border border-neutral-300 dark:border-neutral-700 px-4 py-3 text-sm font-semibold cursor-pointer hover:border-[#D4A72C]"><RotateCcw size={16}/>Repeat this session</button><button type="button" disabled={busy} onClick={onClose} className="min-h-12 rounded-lg border border-neutral-300 dark:border-neutral-700 px-4 py-3 text-sm font-semibold cursor-pointer hover:border-[#D4A72C]">View session history</button></div>
  <details className="rounded-xl border border-neutral-300 dark:border-neutral-800 p-4"><summary className="cursor-pointer text-sm">Setup, notes & XP</summary><div className="mt-4 space-y-4">{session&&<div className="space-y-2 text-sm"><p><strong>Setup:</strong> {session.setupSnapshot.name}</p>{session.practiceSurface&&<p><strong>Surface:</strong> {session.practiceSurface}</p>}<p><strong>Perceived difficulty:</strong> {session.difficultyRating>0?`${session.difficultyRating}/5`:'Not rated'}</p>{session.notes&&<p className="whitespace-pre-wrap break-words"><strong>Notes:</strong> {session.notes}</p>}</div>}<RewardBreakdown reward={reward}/></div></details>
 </div>}</Modal>;
}
