import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {Modal} from '../common/Modal';
import {InventoryPart,PartKind,PART_KINDS,PART_FIELDS,PART_LABELS,uid,setupFromParts,setupUsed,partName,partLabel} from '../../domain/hardware';
import {SetupData} from '../../domain/types';
export const HW_INPUT='w-full min-w-0 rounded-lg border border-neutral-300 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-950 px-3 py-2 text-sm';
export const HW_BUTTON='cursor-pointer rounded-lg border border-[#D4A72C] px-3 py-2 text-sm text-[#8A6500] dark:text-[#D4A72C] hover:bg-[#D4A72C] hover:text-neutral-950 disabled:opacity-40';
export function PartEditor({kind,onSave,onCancel}:{kind:PartKind;onSave:(p:InventoryPart)=>Promise<void>;onCancel:()=>void}) {
 const [name,N]=useState(''),[specs,S]=useState<Record<string,string>>({}),[busy,Z]=useState(false),[error,E]=useState('');
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;Z(true);E('');try{const plies=specs['Number of plies'];if(plies&&(!Number.isInteger(Number(plies))||Number(plies)<1))throw Error('Number of plies must be a positive whole number.');await onSave({id:uid('part'),kind,name:name.trim(),specs});}catch(e){E(e instanceof Error?e.message:'Could not save part.');}finally{Z(false);}}}>
  <p className="text-xs text-neutral-500">Unknown specifications can be left blank. Parts stay available when you use them in a setup configuration.</p>
  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="sm:col-span-2">Name/Brand<input required maxLength={100} className={HW_INPUT} value={name} onChange={e=>N(e.target.value)} placeholder="e.g. Ethical"/></label>
  {Object.entries(PART_FIELDS[kind]).map(([key,options])=><label key={key}>{key}{options?<select className={HW_INPUT} value={specs[key]||''} onChange={e=>S({...specs,[key]:e.target.value})}><option value="">Unknown / skip</option>{options.map(o=><option key={o}>{o}</option>)}</select>:<input maxLength={100} type={/\(mm\)|plies/.test(key)?'number':'text'} min={key==='Number of plies'?1:/\(mm\)/.test(key)?0.01:undefined} list={key==='Number of plies'?'deck-ply-counts':undefined} step={key==='Number of plies'?1:'any'} className={HW_INPUT} value={specs[key]||''} onChange={e=>S({...specs,[key]:e.target.value})}/>}</label>)}</div>
  <datalist id="deck-ply-counts"><option value="5"/><option value="6"/><option value="7"/></datalist>
  {error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex justify-end gap-3"><button type="button" className={HW_BUTTON} disabled={busy} onClick={onCancel}>Cancel</button><button className={HW_BUTTON} disabled={busy}>{busy?'Saving…':'Save part'}</button></div>
 </form>;
}
export function SetupEditor({existing,onSave,onCancel}:{existing?:SetupData;onSave:(s:SetupData)=>Promise<void>;onCancel:()=>void}) {
 const {profile,updateProfile}=useApp();const [name,N]=useState(existing?.name||''),[ids,I]=useState(existing?.partIds||{}),[adding,A]=useState<PartKind|null>(null),[busy,Z]=useState(false),[error,E]=useState('');
 if(!profile)return null;
 if(adding)return <><h3 className="font-semibold mb-4">Add {PART_LABELS[adding]}</h3><PartEditor kind={adding} onCancel={()=>A(null)} onSave={async part=>{await updateProfile({...profile,partsInventory:[...(profile.partsInventory||[]),part]});I({...ids,[part.kind]:part.id});A(null);}}/></>;
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();Z(true);E('');try{await onSave(setupFromParts(name,ids,profile.partsInventory||[],existing));}catch(e){E(e instanceof Error?e.message:'Could not save setup.');}finally{Z(false);}}}>
  <label className="block">Setup name<input required maxLength={100} value={name} onChange={e=>N(e.target.value)} className={HW_INPUT} placeholder="e.g. Everyday 34mm"/></label>
  <p className="text-xs text-neutral-500">Build a configuration from your inventory. Unknown or unused parts can be left blank. Configurations become fixed after their first practice session.</p>
  {PART_KINDS.map(kind=><div key={kind} className="flex items-end gap-2"><label className="flex-1 min-w-0 text-sm">{PART_LABELS[kind]}<select className={HW_INPUT} value={ids[kind]||''} onChange={e=>I({...ids,[kind]:e.target.value})}><option value="">Not specified / none</option>{(profile.partsInventory||[]).filter(p=>p.kind===kind).map(p=><option key={p.id} value={p.id}>{partLabel(p)}</option>)}</select></label><button type="button" className={HW_BUTTON} onClick={()=>A(kind)} aria-label={`Add ${PART_LABELS[kind]}`}>+ Add</button></div>)}
  {error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex justify-end gap-3"><button type="button" disabled={busy} className={HW_BUTTON} onClick={onCancel}>Cancel</button><button disabled={busy} className={HW_BUTTON}>{busy?'Saving…':'Save setup'}</button></div>
 </form>;
}
export function HardwareManager({only}:{only?:'inventory'|'setups'}) {
 const {profile,sessions,updateProfile}=useApp();const [category,C]=useState<PartKind|'all'>('all'),[part,P]=useState<PartKind|null>(null),[setup,S]=useState<SetupData|null|undefined>(undefined),[error,E]=useState(''),[busy,Z]=useState(false);
 if(!profile)return null;const inventory=profile.partsInventory||[];
 const save=async(p:typeof profile)=>{Z(true);E('');try{await updateProfile(p);}catch(e){E(e instanceof Error?e.message:'Could not save.');}finally{Z(false);}};
 return <div className="space-y-6">
 {only!=='inventory'&&<section className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Fingerboard Setups ({profile.savedSetups.length})</h2><button className={HW_BUTTON} onClick={()=>S(null)}>+ Add setup</button></div><p className="text-xs text-neutral-500">Favorite configurations appear first when starting practice. Parts remain available for other configurations.</p>{!profile.savedSetups.length&&<p className="text-sm">No setups yet. Add one now or when you start practice.</p>}
 {profile.savedSetups.map(s=>{const fixed=!!s.usedAt||setupUsed(s.id,sessions);return <article key={s.id} className="rounded-lg border border-neutral-200 dark:border-neutral-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{s.name}</h3><p className="text-xs text-neutral-500">{s.deckWidthMm||'Unknown'} mm · {s.wheelMaterial} wheels {fixed?'· Configuration fixed':''}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} aria-pressed={!!s.favorite} className={HW_BUTTON} onClick={()=>void save({...profile,savedSetups:profile.savedSetups.map(x=>x.id===s.id?{...x,favorite:!x.favorite}:x)})}>{s.favorite?'★ Favorite':'☆ Favorite'}</button>{!fixed&&<button className={HW_BUTTON} onClick={()=>S(s)}>Edit</button>}</div></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs">{PART_KINDS.map(k=><div key={k}><span className="text-neutral-500">{PART_LABELS[k]} </span><p>{s.partsSnapshot?.[k]?partLabel(s.partsSnapshot[k]!):'Not specified'}</p></div>)}</div></article>;})}</section>}
 {only!=='setups'&&<section className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Parts Inventory</h2><button className={HW_BUTTON} onClick={()=>P(category==='all'?'deck':category)}>+ Add part</button></div><nav aria-label="Parts categories" className="flex flex-wrap gap-2">{(['all',...PART_KINDS] as const).map(k=><button key={k} aria-pressed={category===k} className={`${HW_BUTTON} ${category===k?'bg-[#D4A72C]/10':''}`} onClick={()=>C(k)}>{k==='all'?'All':PART_LABELS[k]} ({inventory.filter(p=>k==='all'||p.kind===k).length})</button>)}</nav><div className="grid sm:grid-cols-2 gap-3">{inventory.filter(p=>category==='all'||p.kind===category).map(p=><article key={p.id} className="p-4 border border-neutral-200 dark:border-neutral-800 rounded-lg"><h3 className="font-semibold">{partLabel(p)}</h3><p className="text-xs text-neutral-500">{PART_LABELS[p.kind]}</p><dl className="mt-3 text-xs space-y-1">{Object.entries(p.specs).filter(([,v])=>v).map(([k,v])=><div key={k} className="flex justify-between gap-4"><dt className="text-neutral-500">{k}</dt><dd>{v}</dd></div>)}</dl></article>)}</div>{!inventory.length&&<p className="text-sm">Add installed parts and reserve parts here.</p>}</section>}
 {error&&<p role="alert">{error}</p>}
 <Modal isOpen={!!part} title="Add inventory part" onClose={()=>P(null)}>{part&&<><label className="block text-sm mb-4">Part category<select className={HW_INPUT} value={part} onChange={e=>P(e.target.value as PartKind)}>{PART_KINDS.map(k=><option key={k} value={k}>{PART_LABELS[k]}</option>)}</select></label><PartEditor key={part} kind={part} onCancel={()=>P(null)} onSave={async p=>{await updateProfile({...profile,partsInventory:[...inventory,p]});P(null);}}/></>}</Modal>
 <Modal isOpen={setup!==undefined} title={setup?'Edit unused setup':'Configure fingerboard setup'} onClose={()=>S(undefined)}>{setup!==undefined&&<SetupEditor key={setup?.id||'new'} existing={setup||undefined} onCancel={()=>S(undefined)} onSave={async s=>{await updateProfile({...profile,savedSetups:setup?profile.savedSetups.map(x=>x.id===s.id?s:x):[...profile.savedSetups,s]});S(undefined);}}/>}</Modal>
 </div>;
}
