import React,{useMemo,useState,useEffect} from 'react';
import {useApp} from '../../context/AppContext';
import {RiderShowcaseSettings} from '../../domain/types';
import {progressMilestones} from '../../domain/milestones';
import {trickKey} from '../../domain/progression';
import {uniqueChallenges} from '../../domain/selectedChallengePool';
const DEFAULT:RiderShowcaseSettings={bio:'',goal:'',accent:'mustard',featuredTricks:[],featuredMilestones:[],featuredSetupId:'',showStats:true};
const accents={mustard:'#D4A72C',blue:'#60A5FA',purple:'#C084FC',green:'#4ADE80'};
export const RiderShowcase:React.FC=()=>{
 const {profile,sessions,updateProfile,showToast,repeatChallenge}=useApp();
 const saved=profile?.showcase||DEFAULT;const [draft,setDraft]=useState<RiderShowcaseSettings>(saved),[busy,setBusy]=useState(false);
 useEffect(()=>setDraft(profile?.showcase||DEFAULT),[profile?.id,JSON.stringify(profile?.showcase)]);
 const milestones=useMemo(()=>progressMilestones(sessions),[sessions]);
 const tricks=useMemo(()=>uniqueChallenges([...(profile?.trickLibrary||[]).map(t=>t.trickResult),...sessions.map(s=>s.trickResult),...(profile?.bookmarks||[]).map(b=>b.trickResult)]).sort((a,b)=>a.canonicalName.localeCompare(b.canonicalName)),[profile,sessions]);
 if(!profile)return null;
 const accent=accents[saved.accent]||accents.mustard,setup=profile.savedSetups.find(s=>s.id===saved.featuredSetupId);
 const attempted=sessions.filter(s=>s.attemptCount>0),landings=attempted.reduce((n,s)=>n+s.landingCount,0),attempts=attempted.reduce((n,s)=>n+s.attemptCount,0);
 const toggle=(key:'featuredTricks'|'featuredMilestones',id:string)=>{const values=draft[key];if(!values.includes(id)&&values.length>=3){showToast('Choose up to three highlights.');return;}setDraft({...draft,[key]:values.includes(id)?values.filter(v=>v!==id):[...values,id]});};
 const input='w-full rounded-lg border border-neutral-300 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800 px-3 py-2 text-sm';
 return <section className="ds-surface rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 sm:p-6 space-y-5">
  <div className="border-l-4 pl-4 space-y-2" style={{borderColor:accent}}><p className="text-xs uppercase tracking-widest text-neutral-500">Your rider showcase</p><h1 className="text-2xl font-bold break-words">{profile.displayName}</h1>{saved.bio&&<p className="text-sm whitespace-pre-wrap break-words">{saved.bio}</p>}{saved.goal&&<p className="text-sm break-words"><strong>Working toward:</strong> {saved.goal}</p>}</div>
  {saved.showStats&&<div className="grid grid-cols-3 gap-3 text-center">{[['Sessions',attempted.length],['Landings',landings],['Landing rate',attempts?`${Math.round(landings/attempts*100)}%`:'—']].map(([label,value])=><div key={label} className="rounded-lg bg-neutral-100 dark:bg-neutral-800 p-3"><p className="text-lg font-semibold">{value}</p><p className="text-xs text-neutral-500">{label}</p></div>)}</div>}
  {setup&&<p className="text-sm break-words"><strong>Featured setup:</strong> {setup.name} · {setup.deckWidthMm}mm · {setup.wheelMaterial.charAt(0).toUpperCase()+setup.wheelMaterial.slice(1)}</p>}
  {tricks.some(t=>saved.featuredTricks.includes(trickKey(t)))&&<div><h2 className="text-sm font-semibold mb-2">Featured tricks</h2><div className="flex flex-wrap gap-2">{tricks.filter(t=>saved.featuredTricks.includes(trickKey(t))).map(t=><button key={trickKey(t)} type="button" className="cursor-pointer rounded-lg border border-neutral-300 dark:border-neutral-700 px-3 py-2 text-sm text-left break-words" onClick={()=>void repeatChallenge(t).catch(()=>showToast('Could not start practice. Try again.'))}>{t.canonicalName}<span className="block text-xs text-neutral-500">Practice this trick</span></button>)}</div></div>}
  {milestones.some(m=>saved.featuredMilestones.includes(m.id))&&<div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{milestones.filter(m=>saved.featuredMilestones.includes(m.id)).map(m=><div key={m.id} className="rounded-lg border border-neutral-200 dark:border-neutral-700 p-3"><h3 className="text-sm font-semibold">{m.title}</h3><p className="text-xs mt-1 break-words">{m.trickName}</p><p className="text-xs text-neutral-500 mt-1">{m.detail}</p></div>)}</div>}
  {!saved.bio&&!saved.goal&&!saved.featuredTricks.length&&!saved.featuredMilestones.length&&<p className="text-sm text-neutral-500">Make this space yours: add your practice goal and pin the tricks and milestones you’re proud of.</p>}
  <details className="border border-neutral-200 dark:border-neutral-800 p-4"><summary className="cursor-pointer font-semibold text-sm leading-6">Customize rider showcase</summary><form className="mt-4 space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await updateProfile({...profile,showcase:{...draft,bio:draft.bio.trim(),goal:draft.goal.trim()}});showToast('Rider showcase saved.');}catch(e){showToast(e instanceof Error?e.message:'Could not save showcase.');}finally{setBusy(false);}}}>
   <label className="block text-sm">About you<textarea maxLength={280} placeholder="Your fingerboarding story, style, or favorite place to practice" value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})} className={`${input} mt-2`} rows={3}/></label>
   <label className="block text-sm">Current practice goal<input maxLength={140} placeholder="e.g. Land a clean heelflip three times in a row" value={draft.goal} onChange={e=>setDraft({...draft,goal:e.target.value})} className={`${input} mt-2`}/></label>
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="text-sm">Accent<select className={`${input} mt-2`} value={draft.accent} onChange={e=>setDraft({...draft,accent:e.target.value as RiderShowcaseSettings['accent']})}>{Object.keys(accents).map(c=><option key={c} value={c}>{c.charAt(0).toUpperCase()+c.slice(1)}</option>)}</select></label><label className="text-sm">Featured setup<select className={`${input} mt-2`} value={draft.featuredSetupId} onChange={e=>setDraft({...draft,featuredSetupId:e.target.value})}><option value="">None</option>{profile.savedSetups.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
   <label className="flex items-center gap-2 text-sm cursor-pointer"><input type="checkbox" className="accent-[#D4A72C]" checked={draft.showStats} onChange={e=>setDraft({...draft,showStats:e.target.checked})}/>Show practice totals</label>
   <fieldset><legend className="text-sm font-semibold mb-2">Featured tricks · choose up to 3</legend><div className="max-h-52 overflow-y-auto space-y-2">{tricks.map(t=><label key={trickKey(t)} className="flex gap-2 text-sm cursor-pointer"><input type="checkbox" className="accent-[#D4A72C] mt-1" checked={draft.featuredTricks.includes(trickKey(t))} onChange={()=>toggle('featuredTricks',trickKey(t))}/>{t.canonicalName}</label>)}{!tricks.length&&<p className="text-xs text-neutral-500">Add library tricks, bookmarks, or practice sessions first.</p>}</div></fieldset>
   <fieldset><legend className="text-sm font-semibold mb-2">Featured milestones · choose up to 3</legend><div className="max-h-52 overflow-y-auto space-y-2">{milestones.map(m=><label key={m.id} className="flex gap-2 text-sm cursor-pointer"><input type="checkbox" className="accent-[#D4A72C] mt-1" checked={draft.featuredMilestones.includes(m.id)} onChange={()=>toggle('featuredMilestones',m.id)}/><span>{m.title} · {m.trickName}<span className="block text-xs text-neutral-500">{m.detail}</span></span></label>)}{!milestones.length&&<p className="text-xs text-neutral-500">Milestones appear as you record progress.</p>}</div></fieldset>
   <p className="text-xs text-neutral-500">Your showcase is private to your account and saves across devices. Highlights are derived from recorded history and disappear if their source is deleted.</p>
   <button disabled={busy} className="cursor-pointer rounded-lg bg-[#D4A72C] text-neutral-950 px-4 py-2 text-sm font-semibold disabled:opacity-50">{busy?'Saving…':'Save showcase'}</button>
  </form></details>
 </section>;
};
