import { test } from 'node:test';
import assert from 'node:assert/strict';
import { normalizeUsername } from '../../shared/username.mjs';
import { usernameService } from '../service.mjs';
import worker from '../worker.mjs';
const doc=(values,time='1')=>({fields:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,{stringValue:v}])),updateTime:time});
function fake(initial={}){const rows=new Map(Object.entries(initial));return {rows,name:p=>p,get:async p=>rows.get(p)||null,commit:async writes=>{for(const w of writes){const p=w.update?.name||w.delete,current=rows.get(p);if(w.currentDocument?.exists===false&&current||w.currentDocument?.updateTime&&current?.updateTime!==w.currentDocument.updateTime)throw Object.assign(new Error('Conflict'),{status:409});}for(const w of writes){if(w.delete)rows.delete(w.delete);else rows.set(w.update.name,{...w.update,updateTime:'2'});}}};}
const identity=async()=>({localId:'uid1',email:'rider@example.com'});
test('normalization, format and reserved-name checks',()=>{assert.equal(normalizeUsername(' KTNK_FB '),'ktnk_fb');for(const value of ['admin','ROOT','ab','1rider','rider-name','two words','@rider'])assert.throws(()=>normalizeUsername(value));});
test('claim creates owner and index atomically',async()=>{const db=fake(),service=usernameService(db,{identity});assert.deepEqual(await service.claim('valid','Rider_1'),{username:'rider_1'});assert.equal(db.rows.get('usernames/rider_1').fields.uid.stringValue,'uid1');assert.equal(db.rows.get('usernameOwners/uid1').fields.email.stringValue,'rider@example.com');});
test('another rider cannot claim an occupied username',async()=>{const db=fake({'usernames/rider_1':doc({uid:'someone_else'})});await assert.rejects(usernameService(db,{identity}).claim('valid','rider_1'),e=>e.status===409);assert.equal(db.rows.size,1);});
test('rename frees old username and updates owner together',async()=>{const db=fake({'usernames/old_name':doc({uid:'uid1'}),'usernameOwners/uid1':doc({username:'old_name',email:'old@example.com'})});await usernameService(db,{identity}).claim('valid','new_name');assert.equal(db.rows.has('usernames/old_name'),false);assert.equal(db.rows.get('usernameOwners/uid1').fields.username.stringValue,'new_name');});
test('concurrent claim conflict fails without partial writes',async()=>{const db=fake();db.commit=async()=>{throw Object.assign(new Error('Conflict'),{status:412});};await assert.rejects(usernameService(db,{identity}).claim('valid','rider_1'),e=>e.status===409);assert.equal(db.rows.size,0);});
test('wrong password never reveals email',async()=>{const db=fake({'usernames/rider_1':doc({uid:'uid1'}),'usernameOwners/uid1':doc({username:'rider_1',email:'private@example.com'})});const service=usernameService(db,{identity,password:async()=>{throw Object.assign(new Error('Username or password is incorrect.'),{status:401});}});await assert.rejects(service.login('rider_1','wrong'),e=>e.status===401&&!e.message.includes('private@example.com'));});
test('verified password resolves only the exact owner UID',async()=>{const db=fake({'usernames/rider_1':doc({uid:'uid1'}),'usernameOwners/uid1':doc({username:'rider_1',email:'private@example.com'})});let matched;const service=usernameService(db,{identity,password:async(email,password)=>{matched=[email,password];return {localId:'uid1'};}});assert.deepEqual(await service.login('RIDER_1','good-password'),{email:'private@example.com'});assert.deepEqual(matched,['private@example.com','good-password']);});
test('stale alias cannot log in to a reassigned email account',async()=>{const db=fake({'usernames/rider_1':doc({uid:'uid1'}),'usernameOwners/uid1':doc({username:'rider_1',email:'reassigned@example.com'})});await assert.rejects(usernameService(db,{identity,password:async()=>({localId:'other_uid'})}).login('rider_1','password'),e=>e.status===401);});
test('unknown usernames and invalid names have generic errors',async()=>{const service=usernameService(fake(),{identity});for(const value of ['missing_user','invalid name'])await assert.rejects(service.login(value,'password'),e=>e.status===401&&e.message==='Username or password is incorrect.');});
test('username assignment requires authenticated identity',async()=>{const db=fake();await assert.rejects(usernameService(db,{identity:async()=>{throw new Error('No session');}}).claim('bad','rider_1'));assert.equal(db.rows.size,0);});
test('Worker rejects foreign origins and throttles before credential access',async()=>{const env={ALLOWED_ORIGINS:'https://the-dark-slide-fe8a4.web.app',IP_LIMITER:{limit:async()=>({success:false})},USERNAME_LIMITER:{}};assert.equal((await worker.fetch(new Request('https://worker.example/login',{method:'POST',headers:{Origin:'https://evil.example'}}),env)).status,403);assert.equal((await worker.fetch(new Request('https://worker.example/login',{method:'POST',headers:{Origin:'https://the-dark-slide-fe8a4.web.app'}}),env)).status,429);});
test('Firestore FAILED_PRECONDITION becomes a retryable username conflict',async()=>{const db=fake();db.commit=async()=>{throw Object.assign(new Error('Precondition'),{status:400,reason:'FAILED_PRECONDITION'});};await assert.rejects(usernameService(db,{identity}).claim('valid','rider_1'),e=>e.status===409);});
test('OAuth JWT is signed with valid RS256 and preserves payload',async()=>{
 const {generateKeyPairSync,verify}=await import('node:crypto');const {signedJwt}=await import('../google.mjs');const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
 const payload={iss:'test@example.com',aud:'https://oauth2.googleapis.com/token',scope:'https://www.googleapis.com/auth/datastore',iat:100,exp:3700};
 const jwt=await signedJwt(payload,{private_key:privateKey.export({type:'pkcs8',format:'pem'})});const [header,body,signature]=jwt.split('.');assert.equal(JSON.parse(Buffer.from(header,'base64url')).alg,'RS256');assert.deepEqual(JSON.parse(Buffer.from(body,'base64url')),payload);assert.equal(verify('RSA-SHA256',Buffer.from(header+'.'+body),publicKey,Buffer.from(signature,'base64url')),true);
});
