import {riderSetupAnswers,riderObstacles} from '../../domain/riderSetup';
import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {HardwareManager,HW_INPUT,HW_BUTTON} from '../settings/HardwareManager';
const GOALS=['Improve my fingerboarding','Track my progress','Spot my weak points','Build consistency','Learn new tricks','Get practice ideas','Compare my setups','Join shared challenges'];
const SOURCES=['Invited by KTNK to beta test','A friend','A fingerboarding group','Reddit','Facebook','Discord','Other'];
const EXPERIENCE=['Beginner — working toward consistent ollies','Intermediate — ollies are reliable; kickflips are still developing','Experienced — ollies and kickflips in all four stances','Expert — comfortable with difficult tricks and combinations','Pro — strong board control and consistent obstacle tricks'];
export function RiderOnboarding(){
 const {profile,updateProfile,logout}=useApp();const [busy,B]=useState(false),[error,E]=useState(''),[draft,D]=useState<Record<string,string|string[]>>(riderSetupAnswers(profile?.onboarding?.answers,profile?.savedSetups||[]));
 if(!profile)return null;const step=Math.max(1,profile.onboarding?.step||0);
 const titles=['Your Fingerboard Setups','Your parts inventory','Build your setups','Your experience','Your practice goals','A little more about you','Ready to ride'];
 const answer=(key:string,value:string|string[])=>D({...draft,[key]:value});
 const advance=async(skip=false)=>{B(true);E('');try{await updateProfile({...profile,...(!skip&&step===5&&Array.isArray(draft.obstacles)&&draft.obstacles.length?{availableObstacles:riderObstacles(draft.obstacles)}:{}),onboarding:{version:1,step:Math.min(step+1,6),answers:skip?profile.onboarding?.answers||{}:draft,...(step===6?{completedAt:new Date().toISOString()}: {})}});window.scrollTo({top:0});}catch(e){E(e instanceof Error?e.message:'Could not save rider setup.');}finally{B(false);}};
 const text=(key:string,label:string)=><label className="block space-y-2">{label}<input className={HW_INPUT} value={typeof draft[key]==='string'?draft[key]:''} onChange={e=>answer(key,e.target.value)} maxLength={200}/></label>;
 const multi=(key:string,items:string[])=>{const values=Array.isArray(draft[key])?draft[key]:[];return <div className="grid sm:grid-cols-2 gap-3">{items.map(x=><label key={x} className="flex items-start gap-3 p-3 rounded-lg border border-neutral-300 dark:border-neutral-700 cursor-pointer"><input type="checkbox" className="mt-1 accent-[#D4A72C]" checked={values.includes(x)} onChange={()=>answer(key,values.includes(x)?values.filter(v=>v!==x):[...values,x])}/>{x}</label>)}</div>;};
 return <section className="max-w-4xl mx-auto bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-2xl p-5 sm:p-8 space-y-6"><div className="pb-5 border-b border-neutral-200 dark:border-neutral-800"><p className="text-xs uppercase tracking-wider text-[#D4A72C]">Make Dark Slide yours · Step {step} / 6</p><h1 className="text-2xl font-semibold mt-2">{titles[step]}</h1><div role="progressbar" aria-label="Rider setup progress" aria-valuemin={0} aria-valuemax={6} aria-valuenow={step} className="h-2 w-full mt-5 rounded-full bg-neutral-200 dark:bg-neutral-800 overflow-hidden"><div className="h-full rounded-full" style={{width:`${step/6*100}%`,backgroundColor:'#D4A72C'}}/></div></div>

 {step===1&&<HardwareManager only="inventory"/>}{step===2&&<HardwareManager only="setups"/>}
 {step===3&&<fieldset className="space-y-3"><legend className="mb-3">Which description best matches your current riding?</legend>{EXPERIENCE.map(x=><label key={x} className="flex gap-3 p-4 border rounded-lg border-neutral-300 dark:border-neutral-700 cursor-pointer"><input type="radio" name="experience" checked={draft.experience===x} onChange={()=>answer('experience',x)}/>{x}</label>)}</fieldset>}
 {step===4&&<><h2>What would you like Dark Slide to help you with?</h2>{multi('goals',GOALS)}{text('practiceFocus','Any particular tricks you want to learn?')}</>}
 {step===5&&<div className="space-y-5"><label className="block">Where did you hear about Dark Slide?<select className={HW_INPUT} value={draft.source as string||''} onChange={e=>answer('source',e.target.value)}><option value="">Skip / not sure</option>{SOURCES.map(x=><option key={x}>{x}</option>)}</select></label>{draft.source==='Other'&&text('sourceOther','Tell us where')}{text('sessionLength','Typical practice length (minutes)')}<label className="block">Preferred stance<select className={HW_INPUT} value={draft.preferredStance as string||''} onChange={e=>answer('preferredStance',e.target.value)}><option value="">No preference / skip</option>{['Regular','Fakie','Switch','Nollie'].map(x=><option key={x}>{x}</option>)}</select></label><h2>Which obstacles can you practice on?</h2>{multi('obstacles',['Ledge','Rail','Flatground'])}</div>}
 {step===6&&<div className="space-y-3"><h2 className="text-xl">You’re ready for your first session.</h2><p>{profile.savedSetups.length} configurations · {(profile.partsInventory||[]).length} inventory entries</p><p className="text-sm text-neutral-500">You can revisit your answers and hardware in Rider Profile. Your first session will ask for a setup, a goal, a timer, and a surface.</p></div>}
 {error&&<p role="alert" className="text-red-500">{error}</p>}<div className="flex flex-wrap justify-between gap-3"><button disabled={busy} className={HW_BUTTON} onClick={logout}>Sign out</button><div className="flex flex-wrap gap-3">{step>1&&<button disabled={busy} className={HW_BUTTON} onClick={()=>{B(true);void updateProfile({...profile,onboarding:{version:1,step:step-1,answers:draft}}).catch(e=>E(e.message)).finally(()=>B(false));}}>Back</button>}{step<6&&<button disabled={busy} className={HW_BUTTON} onClick={()=>void advance(true)}>Skip this step</button>}<button disabled={busy} className={`${HW_BUTTON} bg-[#D4A72C]/10`} onClick={()=>void advance()}>{busy?'Saving…':step===6?'Finish rider setup':'Save & continue'}</button></div></div></section>;
}
